import json
import os
import yaml

# get current directory
current_dir = os.path.dirname(os.path.realpath(__file__))

# read yaml as dictionary
with open(current_dir + "/../params.yaml", "r") as f:
    params = yaml.safe_load(f)

features_blood = [
    "WBC_10_9_L",
    "RBC_10_12_L",
    "HGB_g_L",
    "HCT_PCT",
    "MCV_fL",
    "MCH_pg",
    "MCHC_g_dL",
    "PLT_10_9_L",
    "RDW_SD_fL",
    "RDW_CV_PCT",
    "PDW_fL",
    "MPV_fL",
    "P_LCR_PCT",
    "PCT_PCT",
    "NRBC_10_9_L",
    "NRBC_PCT",
    "NEUT_10_9_L",
    "LYMPH_10_9_L",
    "MONO_10_9_L",
    "EO_10_9_L",
    "BASO_10_9_L",
    "NEUT_PCT",
    "LYMPH_PCT",
    "MONO_PCT",
    "EO_PCT",
    "BASO_PCT",
    "IG_10_9_L",
    "IG_PCT",
    "RET_PCT",
    "RET_10_6_uL",
    "IRF_PCT",
    "LFR_PCT",
    "MFR_PCT",
    "HFR_PCT",
    "RET_He_pg",
    "IPF",
    "PLT_I_10_9_L",
    "MicroR_PCT",
    "MacroR_PCT",
    "TNC_10_9_L",
    "WBC_N_10_9_L",
    "TNC_N_10_9_L",
    "BA_N_10_9_L",
    "BA_N_PCT",
    "WBC_D_10_9_L",
    "TNC_D_10_9_L",
    "NEUTx_10_9_L",
    "NEUTx_PCT",
    "LYMP_10_9_L",
    "LYMP_PCT",
    "BA_D_10_9_L",
    "BA_D_PCT",
    "NE_SSC_ch",
    "NE_SFL_ch",
    "NE_FSC_ch",
    "LY_X_ch",
    "LY_Y_ch",
    "LY_Z_ch",
    "MO_X_ch",
    "MO_Y_ch",
    "MO_Z_ch",
    "NE_WX",
    "NE_WY",
    "NE_WZ",
    "LY_WX",
    "LY_WY",
    "LY_WZ",
    "MO_WX",
    "MO_WY",
    "MO_WZ",
    "RBC_O_10_12_L",
    "PLT_O_10_9_L",
    "RBC_He_pg",
    "Delta_He_pg",
    "RET_Y_ch",
    "RET_RBC_Y_ch",
    "IRF_Y_ch",
    "HYPO_He_PCT",
    "HYPER_He_PCT",
    "RPI",
    "RET_UPP",
    "RET_TNC",
    "PLT_F_10_9_L",
    "H_IPF",
    "IPFx_10_9_L",
]

baseline_blood_feats = [x + "_bl" for x in features_blood]
twoyear_blood_feats = [x + "_24m" for x in features_blood]
fouryear_blood_feats = [x + "_48m" for x in features_blood]

rich_with_units = [
    "WBC (per nL)",
    "RBC (per pL)",
    "HGB (g/L)",
    "HCT (%)",
    "MCV (fL)",
    "MCH (pg)",
    "MCHC (g/dL)",
    "PLT (per nL)",
    "RDW-SD (fL)",
    "RDW-CV (%)",
    "PDW (fL)",
    "MPV (fL)",
    "P-LCR (%)",
    "PCT (%)",
    "NRBC# (per nL)",
    "NRBC% (%)",
    "NEUT# (per nL)",
    "LYMPH# (per nL)",
    "MONO# (per nL)",
    "EO# (per nL)",
    "BASO# (per nL)",
    "NEUT% (%)",
    "LYMPH% (%)",
    "MONO% (%)",
    "EO% (%)",
    "BASO% (%)",
    "IG# (per nL)",
    "IG% (%)",
    "RET% (%)",
    "RET# (per pL)",
    "IRF (%)",
    "LFR (%)",
    "MFR (%)",
    "HFR (%)",
    "RET-He (pg)",
    "IPF (%)",
    "PLT-I (per nL)",
    "MicroR (%)",
    "MacroR (%)",
    "TNC (per nL)",
    "WBC-N (per nL)",
    "TNC-N (per nL)",
    "BA-N# (per nL)",
    "BA-N% (%)",
    "WBC-D (per nL)",
    "TNC-D (per nL)",
    "NEUT#& (per nL)",
    "NEUT%& (%)",
    "LYMP#& (per nL)",
    "LYMP%& (%)",
    "BA-D# (per nL)",
    "BA-D% (%)",
    "NE-SSC (ch)",
    "NE-SFL (ch)",
    "NE-FSC (ch)",
    "LY-X (ch)",
    "LY-Y (ch)",
    "LY-Z (ch)",
    "MO-X (ch)",
    "MO-Y (ch)",
    "MO-Z (ch)",
    "NE-WX (‰)",
    "NE-WY (‰)",
    "NE-WZ (‰)",
    "LY-WX (‰)",
    "LY-WY (‰)",
    "LY-WZ (‰)",
    "MO-WX (‰)",
    "MO-WY (‰)",
    "MO-WZ (‰)",
    "RBC-O (per pL)",
    "PLT-O (per nL)",
    "RBC-He (pg)",
    "Delta-He (pg)",
    "RET-Y (ch)",
    "RET-RBC-Y (ch)",
    "IRF-Y (ch)",
    "Hypo-He (%)",
    "Hyper-He (%)",
    "RPI",
    "RET-UPP",
    "RET-TNC",
    "PLT-F (per nL)",
    "H-IPF",
    "IPF# (per nL)",
]

rich_with_units_bl = [string + " (0m)" for string in rich_with_units]
rich_with_units_24m = [string + " (24m)" for string in rich_with_units]
rich_with_units_48m = [string + " (48m)" for string in rich_with_units]

hl_features = [
    "WBC_10_9_L",
    "RBC_10_12_L",
    "HGB_g_L",
    "HCT_PCT",
    "MCV_fL",
    "MCH_pg",
    "MCHC_g_dL",
    "PLT_10_9_L",
    "RDW_SD_fL",
    "NEUT_10_9_L",
    "LYMPH_10_9_L",
    "MONO_10_9_L",
    "EO_10_9_L",
    "BASO_10_9_L",
    "NRBC_10_9_L",
    "IG_10_9_L",
]

hl_features_bl = [string + "_bl" for string in hl_features]
hl_features_24m = [string + "_24m" for string in hl_features]
hl_features_48m = [string + "_48m" for string in hl_features]


difference_features_24m = [x[:-3] + "_diff_24m" for x in hl_features_bl]

# standard fbc HGB, WBC, PLT, HCT, RBC, MCV, RDW, MCH, MCHC, Neut, Lymph, Mono, Eo, Baso, nRBC, (and for us Immature granulocyte count)
standard_fbc = [
    "WBC_10_9_L",
    "RBC_10_12_L",
    "HGB_g_L",
    "HCT_PCT",
    "MCV_fL",
    "MCH_pg",
    "MCHC_g_dL",
    "PLT_10_9_L",
    "RDW_SD_fL",
    "NEUT_10_9_L",
    "LYMPH_10_9_L",
    "MONO_10_9_L",
    "EO_10_9_L",
    "BASO_10_9_L",
    "NRBC_10_9_L",
    "IG_10_9_L",
]

baseline_feats_without_ret = [
    "WBC_10_9_L_bl",
    "RBC_10_12_L_bl",
    "HGB_g_L_bl",
    "HCT_PCT_bl",
    "MCV_fL_bl",
    "MCH_pg_bl",
    "MCHC_g_dL_bl",
    "PLT_10_9_L_bl",
    "RDW_SD_fL_bl",
    "RDW_CV_PCT_bl",
    "PDW_fL_bl",
    "MPV_fL_bl",
    "P_LCR_PCT_bl",
    "PCT_PCT_bl",
    "NRBC_10_9_L_bl",
    "NRBC_PCT_bl",
    "NEUT_10_9_L_bl",
    "LYMPH_10_9_L_bl",
    "MONO_10_9_L_bl",
    "EO_10_9_L_bl",
    "BASO_10_9_L_bl",
    "NEUT_PCT_bl",
    "LYMPH_PCT_bl",
    "MONO_PCT_bl",
    "EO_PCT_bl",
    "BASO_PCT_bl",
    "IG_10_9_L_bl",
    "IG_PCT_bl",
    # 'RET_PCT_bl',
    # 'RET_10_6_uL_bl',
    # 'IRF_PCT_bl',
    # 'LFR_PCT_bl',
    # 'MFR_PCT_bl',
    # 'HFR_PCT_bl',
    # 'RET_He_pg_bl',
    "IPF_bl",
    "PLT_I_10_9_L_bl",
    "MicroR_PCT_bl",
    "MacroR_PCT_bl",
    "TNC_10_9_L_bl",
    "WBC_N_10_9_L_bl",
    "TNC_N_10_9_L_bl",
    "BA_N_10_9_L_bl",
    "BA_N_PCT_bl",
    "WBC_D_10_9_L_bl",
    "TNC_D_10_9_L_bl",
    "NEUTx_10_9_L_bl",
    "NEUTx_PCT_bl",
    "LYMP_10_9_L_bl",
    "LYMP_PCT_bl",
    "BA_D_10_9_L_bl",
    "BA_D_PCT_bl",
    "NE_SSC_ch_bl",
    "NE_SFL_ch_bl",
    "NE_FSC_ch_bl",
    "LY_X_ch_bl",
    "LY_Y_ch_bl",
    "LY_Z_ch_bl",
    "MO_X_ch_bl",
    "MO_Y_ch_bl",
    "MO_Z_ch_bl",
    "NE_WX_bl",
    "NE_WY_bl",
    "NE_WZ_bl",
    "LY_WX_bl",
    "LY_WY_bl",
    "LY_WZ_bl",
    "MO_WX_bl",
    "MO_WY_bl",
    "MO_WZ_bl",
    # 'RBC_O_10_12_L_bl',
    # 'PLT_O_10_9_L_bl',
    # 'RBC_He_pg_bl',
    # 'Delta_He_pg_bl',
    # 'RET_Y_ch_bl',
    # 'RET_RBC_Y_ch_bl',
    # 'IRF_Y_ch_bl',
    # 'HYPO_He_PCT_bl',
    # 'HYPER_He_PCT_bl',
    "RPI_bl",
    # 'RET_UPP_bl',
    # 'RET_TNC_bl',
    "PLT_F_10_9_L_bl",
    "H_IPF_bl",
    "IPFx_10_9_L_bl",
]

reference_ranges_male = {
    "HGB": {"ReferenceLow": 13, "ReferenceHigh": 18},
    "RBC": {"ReferenceLow": 4.5, "ReferenceHigh": 6.5},
    "HCT": {"ReferenceLow": 40, "ReferenceHigh": 54},
    "MCV": {
        "ReferenceLow": 80,
        "ReferenceHigh": 100,
    },
    "MCH": {"ReferenceLow": 27, "ReferenceHigh": 32},
}
