import json
import os

import yaml

# get current directory
current_dir = os.path.dirname(os.path.realpath(__file__))

# read yaml as dictionary
with open(current_dir + "/../params.yaml", "r") as f:
    params = yaml.safe_load(f)

rich_with_units = [
    "WBC (per nL)",
    "RBC (per pL)",
    "HGB (g/L)",
    "HCT (%)",
    "MCV (fL)",
    "MCH (pg)",
    "MCHC (g/dL)",
    "PLT (per nL)",
    "RDW-SD (fL)",
    "RDW-CV (%)",
    "PDW (fL)",
    "MPV (fL)",
    "P-LCR (%)",
    "PCT (%)",
    "NRBC# (per nL)",
    "NRBC% (%)",
    "NEUT# (per nL)",
    "LYMPH# (per nL)",
    "MONO# (per nL)",
    "EO# (per nL)",
    "BASO# (per nL)",
    "NEUT% (%)",
    "LYMPH% (%)",
    "MONO% (%)",
    "EO% (%)",
    "BASO% (%)",
    "IG# (per nL)",
    "IG% (%)",
    "RET% (%)",
    "RET# (per pL)",
    "IRF (%)",
    "LFR (%)",
    "MFR (%)",
    "HFR (%)",
    "RET-He (pg)",
    "IPF (%)",
    "PLT-I (per nL)",
    "MicroR (%)",
    "MacroR (%)",
    "TNC (per nL)",
    "WBC-N (per nL)",
    "TNC-N (per nL)",
    "BA-N# (per nL)",
    "BA-N% (%)",
    "WBC-D (per nL)",
    "TNC-D (per nL)",
    "NEUT#& (per nL)",
    "NEUT%& (%)",
    "LYMP#& (per nL)",
    "LYMP%& (%)",
    "BA-D# (per nL)",
    "BA-D% (%)",
    "NE-SSC (ch)",
    "NE-SFL (ch)",
    "NE-FSC (ch)",
    "LY-X (ch)",
    "LY-Y (ch)",
    "LY-Z (ch)",
    "MO-X (ch)",
    "MO-Y (ch)",
    "MO-Z (ch)",
    "NE-WX (‰)",
    "NE-WY (‰)",
    "NE-WZ (‰)",
    "LY-WX (‰)",
    "LY-WY (‰)",
    "LY-WZ (‰)",
    "MO-WX (‰)",
    "MO-WY (‰)",
    "MO-WZ (‰)",
    "RBC-O (per pL)",
    "PLT-O (per nL)",
    "RBC-He (pg)",
    "Delta-He (pg)",
    "RET-Y (ch)",
    "RET-RBC-Y (ch)",
    "IRF-Y (ch)",
    "Hypo-He (%)",
    "Hyper-He (%)",
    "RPI",
    "RET-UPP",
    "RET-TNC",
    "PLT-F (per nL)",
    "H-IPF",
    "IPF# (per nL)",
]

rich_with_units_bl = [string + " (0m)" for string in rich_with_units]
rich_with_units_24m = [string + " (24m)" for string in rich_with_units]
rich_with_units_48m = [string + " (48m)" for string in rich_with_units]

hl_features = [
    "WBC_10_9_L",
    "RBC_10_12_L",
    "HGB_g_L",
    "HCT_PCT",
    "MCV_fL",
    "MCH_pg",
    "MCHC_g_dL",
    "PLT_10_9_L",
    "RDW_SD_fL",
    "NEUT_10_9_L",
    "LYMPH_10_9_L",
    "MONO_10_9_L",
    "EO_10_9_L",
    "BASO_10_9_L",
    "NRBC_10_9_L",
    "IG_10_9_L",
]

hl_features_bl = [string + "_bl" for string in hl_features]
hl_features_24m = [string + "_24m" for string in hl_features]
hl_features_48m = [string + "_48m" for string in hl_features]

# standard fbc HGB, WBC, PLT, HCT, RBC, MCV, RDW, MCH, MCHC, Neut, Lymph, Mono, Eo, Baso, nRBC, (and for us Immature granulocyte count)
standard_fbc = [
    "WBC_10_9_L",
    "RBC_10_12_L",
    "HGB_g_L",
    "HCT_PCT",
    "MCV_fL",
    "MCH_pg",
    "MCHC_g_dL",
    "PLT_10_9_L",
    "RDW_SD_fL",
    "NEUT_10_9_L",
    "LYMPH_10_9_L",
    "MONO_10_9_L",
    "EO_10_9_L",
    "BASO_10_9_L",
    "NRBC_10_9_L",
    "IG_10_9_L",
]

baseline_feats_without_ret = [
    "WBC_10_9_L_bl",
    "RBC_10_12_L_bl",
    "HGB_g_L_bl",
    "HCT_PCT_bl",
    "MCV_fL_bl",
    "MCH_pg_bl",
    "MCHC_g_dL_bl",
    "PLT_10_9_L_bl",
    "RDW_SD_fL_bl",
    "RDW_CV_PCT_bl",
    "PDW_fL_bl",
    "MPV_fL_bl",
    "P_LCR_PCT_bl",
    "PCT_PCT_bl",
    "NRBC_10_9_L_bl",
    "NRBC_PCT_bl",
    "NEUT_10_9_L_bl",
    "LYMPH_10_9_L_bl",
    "MONO_10_9_L_bl",
    "EO_10_9_L_bl",
    "BASO_10_9_L_bl",
    "NEUT_PCT_bl",
    "LYMPH_PCT_bl",
    "MONO_PCT_bl",
    "EO_PCT_bl",
    "BASO_PCT_bl",
    "IG_10_9_L_bl",
    "IG_PCT_bl",
    # 'RET_PCT_bl',
    # 'RET_10_6_uL_bl',
    # 'IRF_PCT_bl',
    # 'LFR_PCT_bl',
    # 'MFR_PCT_bl',
    # 'HFR_PCT_bl',
    # 'RET_He_pg_bl',
    "IPF_bl",
    "PLT_I_10_9_L_bl",
    "MicroR_PCT_bl",
    "MacroR_PCT_bl",
    "TNC_10_9_L_bl",
    "WBC_N_10_9_L_bl",
    "TNC_N_10_9_L_bl",
    "BA_N_10_9_L_bl",
    "BA_N_PCT_bl",
    "WBC_D_10_9_L_bl",
    "TNC_D_10_9_L_bl",
    "NEUTx_10_9_L_bl",
    "NEUTx_PCT_bl",
    "LYMP_10_9_L_bl",
    "LYMP_PCT_bl",
    "BA_D_10_9_L_bl",
    "BA_D_PCT_bl",
    "NE_SSC_ch_bl",
    "NE_SFL_ch_bl",
    "NE_FSC_ch_bl",
    "LY_X_ch_bl",
    "LY_Y_ch_bl",
    "LY_Z_ch_bl",
    "MO_X_ch_bl",
    "MO_Y_ch_bl",
    "MO_Z_ch_bl",
    "NE_WX_bl",
    "NE_WY_bl",
    "NE_WZ_bl",
    "LY_WX_bl",
    "LY_WY_bl",
    "LY_WZ_bl",
    "MO_WX_bl",
    "MO_WY_bl",
    "MO_WZ_bl",
    # 'RBC_O_10_12_L_bl',
    # 'PLT_O_10_9_L_bl',
    # 'RBC_He_pg_bl',
    # 'Delta_He_pg_bl',
    # 'RET_Y_ch_bl',
    # 'RET_RBC_Y_ch_bl',
    # 'IRF_Y_ch_bl',
    # 'HYPO_He_PCT_bl',
    # 'HYPER_He_PCT_bl',
    "RPI_bl",
    # 'RET_UPP_bl',
    # 'RET_TNC_bl',
    "PLT_F_10_9_L_bl",
    "H_IPF_bl",
    "IPFx_10_9_L_bl",
]

reference_ranges_male = {
    "HGB": {"ReferenceLow": 13, "ReferenceHigh": 18},
    "RBC": {"ReferenceLow": 4.5, "ReferenceHigh": 6.5},
    "HCT": {"ReferenceLow": 40, "ReferenceHigh": 54},
    "MCV": {
        "ReferenceLow": 80,
        "ReferenceHigh": 100,
    },
    "MCH": {"ReferenceLow": 27, "ReferenceHigh": 32},
}

renaming_dict = {  # from XN_SAMPLE to INTERVAL export nomenclature
    "HGB(g/L)_bl": "HGB_g_L_bl",
    "HGB(g/L)_24m": "HGB_g_L_24m",
    "HGB(g/L)_48m": "HGB_g_L_48m",
    "PLT(10^3/uL)_bl": "PLT_10_9_L_bl",
    "PLT(10^3/uL)_24m": "PLT_10_9_L_24m",
    "PLT(10^3/uL)_48m": "PLT_10_9_L_48m",
    "MCV(fL)_bl": "MCV_fL_bl",
    "MCV(fL)_24m": "MCV_fL_24m",
    "MCV(fL)_48m": "MCV_fL_48m",
    "MCH(pg)_bl": "MCH_pg_bl",
    "MCH(pg)_24m": "MCH_pg_24m",
    "MCH(pg)_48m": "MCH_pg_48m",
    "MCHC(g/dL)_bl": "MCHC_g_dL_bl",
    "MCHC(g/dL)_24m": "MCHC_g_dL_24m",
    "MCHC(g/dL)_48m": "MCHC_g_dL_48m",
    "HCT(%)_bl": "HCT_PCT_bl",
    "HCT(%)_24m": "HCT_PCT_24m",
    "HCT(%)_48m": "HCT_PCT_48m",
    "WBC(10^3/uL)_bl": "WBC_10_9_L_bl",
    "WBC(10^3/uL)_24m": "WBC_10_9_L_24m",
    "WBC(10^3/uL)_48m": "WBC_10_9_L_48m",
    "RBC(10^6/uL)_bl": "RBC_10_12_L_bl",
    "RBC(10^6/uL)_24m": "RBC_10_12_L_24m",
    "RBC(10^6/uL)_48m": "RBC_10_12_L_48m",
    "RDW-SD(fL)_bl": "RDW_SD_fL_bl",
    "RDW-SD(fL)_24m": "RDW_SD_fL_24m",
    "RDW-SD(fL)_48m": "RDW_SD_fL_48m",
    "RDW-CV(%)_bl": "RDW_CV_PCT_bl",
    "RDW-CV(%)_24m": "RDW_CV_PCT_24m",
    "RDW-CV(%)_48m": "RDW_CV_PCT_48m",
    "PDW(fL)_bl": "PDW_fL_bl",
    "PDW(fL)_24m": "PDW_fL_24m",
    "PDW(fL)_48m": "PDW_fL_48m",
    "MPV(fL)_bl": "MPV_fL_bl",
    "MPV(fL)_24m": "MPV_fL_24m",
    "MPV(fL)_48m": "MPV_fL_48m",
    "P-LCR(%)_bl": "P_LCR_PCT_bl",
    "P-LCR(%)_24m": "P_LCR_PCT_24m",
    "P-LCR(%)_48m": "P_LCR_PCT_48m",
    "PCT(%)_bl": "PCT_PCT_bl",
    "PCT(%)_24m": "PCT_PCT_24m",
    "PCT(%)_48m": "PCT_PCT_48m",
    "NRBC#(10^3/uL)_bl": "NRBC_10_9_L_bl",
    "NRBC#(10^3/uL)_24m": "NRBC_10_9_L_24m",
    "NRBC#(10^3/uL)_48m": "NRBC_10_9_L_48m",
    "NRBC%(%)_bl": "NRBC_PCT_bl",
    "NRBC%(%)_24m": "NRBC_PCT_24m",
    "NRBC%(%)_48m": "NRBC_PCT_48m",
    "NEUT#(10^3/uL)_bl": "NEUT_10_9_L_bl",
    "NEUT#(10^3/uL)_24m": "NEUT_10_9_L_24m",
    "NEUT#(10^3/uL)_48m": "NEUT_10_9_L_48m",
    "LYMPH#(10^3/uL)_bl": "LYMPH_10_9_L_bl",
    "LYMPH#(10^3/uL)_24m": "LYMPH_10_9_L_24m",
    "LYMPH#(10^3/uL)_48m": "LYMPH_10_9_L_48m",
    "MONO#(10^3/uL)_bl": "MONO_10_9_L_bl",
    "MONO#(10^3/uL)_24m": "MONO_10_9_L_24m",
    "MONO#(10^3/uL)_48m": "MONO_10_9_L_48m",
    "EO#(10^3/uL)_bl": "EO_10_9_L_bl",
    "EO#(10^3/uL)_24m": "EO_10_9_L_24m",
    "EO#(10^3/uL)_48m": "EO_10_9_L_48m",
    "BASO#(10^3/uL)_bl": "BASO_10_9_L_bl",
    "BASO#(10^3/uL)_24m": "BASO_10_9_L_24m",
    "BASO#(10^3/uL)_48m": "BASO_10_9_L_48m",
    "NEUT%(%)_bl": "NEUT_PCT_bl",
    "NEUT%(%)_24m": "NEUT_PCT_24m",
    "NEUT%(%)_48m": "NEUT_PCT_48m",
    "LYMPH%(%)_bl": "LYMPH_PCT_bl",
    "LYMPH%(%)_24m": "LYMPH_PCT_24m",
    "LYMPH%(%)_48m": "LYMPH_PCT_48m",
    "MONO%(%)_bl": "MONO_PCT_bl",
    "MONO%(%)_24m": "MONO_PCT_24m",
    "MONO%(%)_48m": "MONO_PCT_48m",
    "EO%(%)_bl": "EO_PCT_bl",
    "EO%(%)_24m": "EO_PCT_24m",
    "EO%(%)_48m": "EO_PCT_48m",
    "BASO%(%)_bl": "BASO_PCT_bl",
    "BASO%(%)_24m": "BASO_PCT_24m",
    "BASO%(%)_48m": "BASO_PCT_48m",
    "IG#(10^3/uL)_bl": "IG_10_9_L_bl",
    "IG#(10^3/uL)_24m": "IG_10_9_L_24m",
    "IG#(10^3/uL)_48m": "IG_10_9_L_48m",
    "IG%(%)_bl": "IG_PCT_bl",
    "IG%(%)_24m": "IG_PCT_24m",
    "IG%(%)_48m": "IG_PCT_48m",
    "RET%(%)_bl": "RET_PCT_bl",
    "RET%(%)_24m": "RET_PCT_24m",
    "RET%(%)_48m": "RET_PCT_48m",
    "RET#(10^6/uL)_bl": "RET_10_6_uL_bl",
    "RET#(10^6/uL)_24m": "RET_10_6_uL_24m",
    "RET#(10^6/uL)_48m": "RET_10_6_uL_48m",
    "IRF(%)_bl": "IRF_PCT_bl",
    "IRF(%)_24m": "IRF_PCT_24m",
    "IRF(%)_48m": "IRF_PCT_48m",
    "LFR(%)_bl": "LFR_PCT_bl",
    "LFR(%)_24m": "LFR_PCT_24m",
    "LFR(%)_48m": "LFR_PCT_48m",
    "MFR(%)_bl": "MFR_PCT_bl",
    "MFR(%)_24m": "MFR_PCT_24m",
    "MFR(%)_48m": "MFR_PCT_48m",
    "HFR(%)_bl": "HFR_PCT_bl",
    "HFR(%)_24m": "HFR_PCT_24m",
    "HFR(%)_48m": "HFR_PCT_48m",
    "RET-He(pg)_bl": "RET_He_pg_bl",
    "RET-He(pg)_24m": "RET_He_pg_24m",
    "RET-He(pg)_48m": "RET_He_pg_48m",
    "IPF(%)_bl": "IPF_bl",
    "IPF(%)_24m": "IPF_24m",
    "IPF(%)_48m": "IPF_48m",
    "PLT-I(10^3/uL)_bl": "PLT_I_10_9_L_bl",
    "PLT-I(10^3/uL)_24m": "PLT_I_10_9_L_24m",
    "PLT-I(10^3/uL)_48m": "PLT_I_10_9_L_48m",
    "MicroR(%)_bl": "MicroR_PCT_bl",
    "MicroR(%)_24m": "MicroR_PCT_24m",
    "MicroR(%)_48m": "MicroR_PCT_48m",
    "MacroR(%)_bl": "MacroR_PCT_bl",
    "MacroR(%)_24m": "MacroR_PCT_24m",
    "MacroR(%)_48m": "MacroR_PCT_48m",
    "TNC(10^3/uL)_bl": "TNC_10_9_L_bl",
    "TNC(10^3/uL)_24m": "TNC_10_9_L_24m",
    "TNC(10^3/uL)_48m": "TNC_10_9_L_48m",
    "WBC-N(10^3/uL)_bl": "WBC_N_10_9_L_bl",
    "WBC-N(10^3/uL)_24m": "WBC_N_10_9_L_24m",
    "WBC-N(10^3/uL)_48m": "WBC_N_10_9_L_48m",
    "TNC-N(10^3/uL)_bl": "TNC_N_10_9_L_bl",
    "TNC-N(10^3/uL)_24m": "TNC_N_10_9_L_24m",
    "TNC-N(10^3/uL)_48m": "TNC_N_10_9_L_48m",
    "BA-N#(10^3/uL)_bl": "BA_N_10_9_L_bl",
    "BA-N#(10^3/uL)_24m": "BA_N_10_9_L_24m",
    "BA-N#(10^3/uL)_48m": "BA_N_10_9_L_48m",
    "BA-N%(%)_bl": "BA_N_PCT_bl",
    "BA-N%(%)_24m": "BA_N_PCT_24m",
    "BA-N%(%)_48m": "BA_N_PCT_48m",
    "WBC-D(10^3/uL)_bl": "WBC_D_10_9_L_bl",
    "WBC-D(10^3/uL)_24m": "WBC_D_10_9_L_24m",
    "WBC-D(10^3/uL)_48m": "WBC_D_10_9_L_48m",
    "TNC-D(10^3/uL)_bl": "TNC_D_10_9_L_bl",
    "TNC-D(10^3/uL)_24m": "TNC_D_10_9_L_24m",
    "TNC-D(10^3/uL)_48m": "TNC_D_10_9_L_48m",
    "NEUT#&(10^3/uL)_bl": "NEUTx_10_9_L_bl",
    "NEUT#&(10^3/uL)_24m": "NEUTx_10_9_L_24m",
    "NEUT#&(10^3/uL)_48m": "NEUTx_10_9_L_48m",
    "NEUT%&(%)_bl": "NEUTx_PCT_bl",
    "NEUT%&(%)_24m": "NEUTx_PCT_24m",
    "NEUT%&(%)_48m": "NEUTx_PCT_48m",
    "LYMP#&(10^3/uL)_bl": "LYMP_10_9_L_bl",
    "LYMP#&(10^3/uL)_24m": "LYMP_10_9_L_24m",
    "LYMP#&(10^3/uL)_48m": "LYMP_10_9_L_48m",
    "LYMP%&(%)_bl": "LYMP_PCT_bl",
    "LYMP%&(%)_24m": "LYMP_PCT_24m",
    "LYMP%&(%)_48m": "LYMP_PCT_48m",
    "BA-D#(10^3/uL)_bl": "BA_D_10_9_L_bl",
    "BA-D#(10^3/uL)_24m": "BA_D_10_9_L_24m",
    "BA-D#(10^3/uL)_48m": "BA_D_10_9_L_48m",
    "BA-D%(%)_bl": "BA_D_PCT_bl",
    "BA-D%(%)_24m": "BA_D_PCT_24m",
    "BA-D%(%)_48m": "BA_D_PCT_48m",
    "NE-SSC(ch)_bl": "NE_SSC_ch_bl",
    "NE-SSC(ch)_24m": "NE_SSC_ch_24m",
    "NE-SSC(ch)_48m": "NE_SSC_ch_48m",
    "NE-SFL(ch)_bl": "NE_SFL_ch_bl",
    "NE-SFL(ch)_24m": "NE_SFL_ch_24m",
    "NE-SFL(ch)_48m": "NE_SFL_ch_48m",
    "NE-FSC(ch)_bl": "NE_FSC_ch_bl",
    "NE-FSC(ch)_24m": "NE_FSC_ch_24m",
    "NE-FSC(ch)_48m": "NE_FSC_ch_48m",
    "LY-X(ch)_bl": "LY_X_ch_bl",
    "LY-X(ch)_24m": "LY_X_ch_24m",
    "LY-X(ch)_48m": "LY_X_ch_48m",
    "LY-Y(ch)_bl": "LY_Y_ch_bl",
    "LY-Y(ch)_24m": "LY_Y_ch_24m",
    "LY-Y(ch)_48m": "LY_Y_ch_48m",
    "LY-Z(ch)_bl": "LY_Z_ch_bl",
    "LY-Z(ch)_24m": "LY_Z_ch_24m",
    "LY-Z(ch)_48m": "LY_Z_ch_48m",
    "MO-X(ch)_bl": "MO_X_ch_bl",
    "MO-X(ch)_24m": "MO_X_ch_24m",
    "MO-X(ch)_48m": "MO_X_ch_48m",
    "MO-Y(ch)_bl": "MO_Y_ch_bl",
    "MO-Y(ch)_24m": "MO_Y_ch_24m",
    "MO-Y(ch)_48m": "MO_Y_ch_48m",
    "MO-Z(ch)_bl": "MO_Z_ch_bl",
    "MO-Z(ch)_24m": "MO_Z_ch_24m",
    "MO-Z(ch)_48m": "MO_Z_ch_48m",
    "NE-WX()_bl": "NE_WX_bl",
    "NE-WX()_24m": "NE_WX_24m",
    "NE-WX()_48m": "NE_WX_48m",
    "NE-WY()_bl": "NE_WY_bl",
    "NE-WY()_24m": "NE_WY_24m",
    "NE-WY()_48m": "NE_WY_48m",
    "NE-WZ()_bl": "NE_WZ_bl",
    "NE-WZ()_24m": "NE_WZ_24m",
    "NE-WZ()_48m": "NE_WZ_48m",
    "LY-WX()_bl": "LY_WX_bl",
    "LY-WX()_24m": "LY_WX_24m",
    "LY-WX()_48m": "LY_WX_48m",
    "LY-WY()_bl": "LY_WY_bl",
    "LY-WY()_24m": "LY_WY_24m",
    "LY-WY()_48m": "LY_WY_48m",
    "LY-WZ()_bl": "LY_WZ_bl",
    "LY-WZ()_24m": "LY_WZ_24m",
    "LY-WZ()_48m": "LY_WZ_48m",
    "MO-WX()_bl": "MO_WX_bl",
    "MO-WX()_24m": "MO_WX_24m",
    "MO-WX()_48m": "MO_WX_48m",
    "MO-WY()_bl": "MO_WY_bl",
    "MO-WY()_24m": "MO_WY_24m",
    "MO-WY()_48m": "MO_WY_48m",
    "MO-WZ()_bl": "MO_WZ_bl",
    "MO-WZ()_24m": "MO_WZ_24m",
    "MO-WZ()_48m": "MO_WZ_48m",
    "RBC-O(10^6/uL)_bl": "RBC_O_10_12_L_bl",
    "RBC-O(10^6/uL)_24m": "RBC_O_10_12_L_24m",
    "RBC-O(10^6/uL)_48m": "RBC_O_10_12_L_48m",
    "PLT-O(10^3/uL)_bl": "PLT_O_10_9_L_bl",
    "PLT-O(10^3/uL)_24m": "PLT_O_10_9_L_24m",
    "PLT-O(10^3/uL)_48m": "PLT_O_10_9_L_48m",
    "RBC-He(pg)_bl": "RBC_He_pg_bl",
    "RBC-He(pg)_24m": "RBC_He_pg_24m",
    "RBC-He(pg)_48m": "RBC_He_pg_48m",
    "Delta-He(pg)_bl": "Delta_He_pg_bl",
    "Delta-He(pg)_24m": "Delta_He_pg_24m",
    "Delta-He(pg)_48m": "Delta_He_pg_48m",
    "RET-Y(ch)_bl": "RET_Y_ch_bl",
    "RET-Y(ch)_24m": "RET_Y_ch_24m",
    "RET-Y(ch)_48m": "RET_Y_ch_48m",
    "RET-RBC-Y(ch)_bl": "RET_RBC_Y_ch_bl",
    "RET-RBC-Y(ch)_24m": "RET_RBC_Y_ch_24m",
    "RET-RBC-Y(ch)_48m": "RET_RBC_Y_ch_48m",
    "IRF-Y(ch)_bl": "IRF_Y_ch_bl",
    "IRF-Y(ch)_24m": "IRF_Y_ch_24m",
    "IRF-Y(ch)_48m": "IRF_Y_ch_48m",
    "HYPO-He(%)_bl": "HYPO_He_PCT_bl",
    "HYPO-He(%)_24m": "HYPO_He_PCT_24m",
    "HYPO-He(%)_48m": "HYPO_He_PCT_48m",
    "HYPER-He(%)_bl": "HYPER_He_PCT_bl",
    "HYPER-He(%)_24m": "HYPER_He_PCT_24m",
    "HYPER-He(%)_48m": "HYPER_He_PCT_48m",
    "RPI()_bl": "RPI_bl",
    "RPI()_24m": "RPI_24m",
    "RPI()_48m": "RPI_48m",
    "RET-UPP()_bl": "RET_UPP_bl",
    "RET-UPP()_24m": "RET_UPP_24m",
    "RET-UPP()_48m": "RET_UPP_48m",
    "RET-TNC()_bl": "RET_TNC_bl",
    "RET-TNC()_24m": "RET_TNC_24m",
    "RET-TNC()_48m": "RET_TNC_48m",
    "PLT-F(10^3/uL)_bl": "PLT_F_10_9_L_bl",
    "PLT-F(10^3/uL)_24m": "PLT_F_10_9_L_24m",
    "PLT-F(10^3/uL)_48m": "PLT_F_10_9_L_48m",
    "H-IPF(%)_bl": "H_IPF_bl",
    "H-IPF(%)_24m": "H_IPF_24m",
    "H-IPF(%)_48m": "H_IPF_48m",
    "IPF#(10^3/uL)_bl": "IPFx_10_9_L_bl",
    "IPF#(10^3/uL)_24m": "IPFx_10_9_L_24m",
    "IPF#(10^3/uL)_48m": "IPFx_10_9_L_48m",
}

with open(f"{params['out_dir']}/data/decrypt_blood_feats.json", "r") as f:
    decrypt_blood_feats = json.load(f)

baseline_blood_feats = [x for x in decrypt_blood_feats if x.endswith("_bl")]
twoyear_blood_feats = [x for x in decrypt_blood_feats if x.endswith("_24m")]
fouryear_blood_feats = [x for x in decrypt_blood_feats if x.endswith("_48m")]

difference_features_24m = [x[:-3] + "_diff_24m" for x in hl_features_bl]

with open(f"{params['out_dir']}/data/decrypt_blood_feats_uncorr.json", "r") as f:
    uncorr_features = json.load(f)

# drop any features from uncorr_features that contains "YX" or "ZY" or "ZX" in the name
uncorr_features = [
    x for x in uncorr_features if "_YX" not in x and "_ZY" not in x and "_ZX" not in x
]

uncorr_feats_bl = [x + "_bl" for x in uncorr_features]
uncorr_feats_24m = [x + "_24m" for x in uncorr_features]
uncorr_feats_48m = [x + "_48m" for x in uncorr_features]

pretty_name_translation_dict = {
    "AREA-F#()": "Area Fraction",
    "AS-LYMP#(10^3/uL)": "AS Lymphocyte\n Count",
    "AS-LYMP%(%)": "AS Lymphocyte\n Percentage",
    "AS-LYMP%L(%)": "AS Lymphocyte\n Large Percentage",
    "BASO_10_9_L": "BASO",
    "BASO_PCT": "BASO%",
    "BA_D_10_9_L": "Band Cell Count",
    "BA_D_PCT": "Band Cell Percentage",
    "BA_N_10_9_L": "Band Neutrophil\n Count",
    "BA_N_PCT": "Band Neutrophil\n Percentage",
    "DLT-PLT-F()": "Delta Platelet\n Fraction",
    "DLT-PLTO()": "Delta Platelet\n Optical",
    "DLT-RBC()": "Delta RBC",
    "DLT-WBCD()": "Delta WBC Differential",
    "DLT-WBCP()": "Delta WBC Positive",
    "Delta_He_pg": "Delta Haemoglobin\n Equivalent",
    "EO#(hsA)(10^3/uL)": "Eosinophil\n Count (hsA)",
    "EO%(hsA)(%)": "Eosinophil\n Percentage (hsA)",
    "EO-BF#(10^3/uL)": "Eosinophil\n BF Count",
    "EO-BF%(%)": "Eosinophil\n BF Percentage",
    "EO_10_9_L": "EO",
    "EO_PCT": "EO%",
    "Error(Func.)": "Error (Function)",
    "Error(Result)": "Error (Result)",
    "FRC#(10^6/uL)": "FRC Count",
    "FRC%(%)": "FRC Percentage",
    "HCT_PCT": "HCT",
    "HF#(hsA)(10^3/uL)": "High Fluorescence\n Lymphocyte Count (hsA)",
    "HF%(hsA)(/100WBC)": "High Fluorescence\n Lymphocyte Percentage (hsA) (/100WBC)",
    "HFLC#(10^3/uL)": "High Fluorescence\n Lymphocyte Count",
    "HFLC%(%)": "High Fluorescence\n Lymphocyte Percentage",
    "HFR_PCT": "High Fluorescence\n Reticulocyte Percentage",
    "HGB-BLANK()": "Haemoglobin\n Blank",
    "HGB-O(g/dL)": "Haemoglobin\n Optical",
    "HGB-SAMPLE()": "Haemoglobin\n Sample",
    "HPC#(10^3/uL)": "HPC Count",
    "HYPER_He_PCT": "Hyper-He Percentage",
    "HYPO_He_PCT": "Hypo-He Percentage",
    "H_IPF": "High Fluorescence\n Immature Platelet Fraction",
    "IG_10_9_L": "IG",
    "IG_PCT": "IG%",
    "IP SUS(PLT)Giant PLT?": "IP: Giant Platelets\n Suspected?",
    "IP SUS(PLT)PLT Clumps?": "IP: Platelet\n Clumps Suspected?",
    "IP SUS(RBC)Fragments?": "IP: RBC Fragments\n Suspected?",
    "IP SUS(RBC)HGB Defect?": "IP: Haemoglobin\n Defect Suspected?",
    "IP SUS(RBC)Iron Deficiency?": "IP: Iron Deficiency\n Suspected?",
    "IP SUS(RBC)RBC Agglutination?": "IP: RBC Agglutination\n Suspected?",
    "IP SUS(RBC)Turbidity/HGB Interf?": "IP: Turbidity/Haemoglobin\n Interference Suspected?",
    "IP SUS(RBC)pRBC?": "IP: Pathological\n RBC Suspected?",
    "IP SUS(RBC)pRBC?(R)": "IP: Pathological\n RBC Suspected? (Reticulocyte)",
    "IP SUS(WBC)Abn Lymho/L-Blasts?": "IP: Abnormal\n Lymphocytes or Blasts Suspected?",
    "IP SUS(WBC)AbnLymp?": "IP: Abnormal\n Lymphocytes Suspected?",
    "IP SUS(WBC)Atypical Lympho?": "IP: Atypical\n Lymphocytes Suspected?",
    "IP SUS(WBC)Blasts?": "IP: Blasts\n Suspected?",
    "IP SUS(WBC)Left Shift?": "IP: Left Shift\n Suspected?",
    "IPF": "Immature Platelet\n Fraction",
    "IPFx_10_9_L": "Platelet Count\n in IPF area",
    "IRF_PCT": "Immature Reticulocyte\n Fraction Percentage",
    "IRF_Y_ch": "Immature Reticulocyte\n Fraction Y Channel",
    "L-MCV(fL)": "MCV of larger\n RBC dist.",
    "L-RBC(10^6/uL)": "RBC of larger\n RBC dist.",
    "LFR_PCT": "Low Fluorescence\n Ratio Percentage",
    "LY-BF#(10^3/uL)": "Lymphocyte\n BF Count",
    "LY-BF%(%)": "Lymphocyte\n BF Percentage",
    "LYMPH#(hsA)(10^3/uL)": "Lymphocyte\n Count (hsA)",
    "LYMPH%(hsA)(%)": "Lymphocyte\n Percentage (hsA)",
    "LYMPH_PCT": "Lymphocyte\n Percentage",
    "LYMP_10_9_L": "Lymphocyte\n Count",
    "LYMP_PCT": "Lymphocyte\n Percentage",
    "LY_WX": "Lymphocyte\n WX",
    "LY_WY": "Lymphocyte\n WY",
    "LY_WZ": "Lymphocyte\n WZ",
    "LY_X_ch": "Lymphocyte\n X Channel",
    "LY_Y_ch": "Lymphocyte\n Y Channel",
    "LY_Z_ch": "Lymphocyte\n Z Channel",
    "MFR_PCT": "Mid Fluorescence\n Ratio Percentage",
    "MN#(10^3/uL)": "Monocyte Count",
    "MN#(hsA)(10^3/uL)": "Monocyte Count\n (hsA)",
    "MN%(%)": "Monocyte Percentage",
    "MN%(hsA)(%)": "Monocyte Percentage\n (hsA)",
    "MO-BF#(10^3/uL)": "Monocyte BF\n Count",
    "MO-BF%(%)": "Monocyte BF\n Percentage",
    "MONO#(hsA)(10^3/uL)": "Monocyte Count\n (hsA)",
    "MONO%(hsA)(%)": "Monocyte Percentage\n (hsA)",
    "MONO_10_9_L": "MONO",
    "MONO_PCT": "MONO%",
    "MO_WX": "Monocyte WX",
    "MO_WY": "Monocyte WY",
    "MO_WZ": "Monocyte WZ",
    "MO_X_ch": "Monocyte X\n Channel",
    "MO_Y_ch": "Monocyte Y\n Channel",
    "MO_Z_ch": "Monocyte Z\n Channel",
    "MPV_fL": "Mean Platelet\n Volume",
    "MacroR_PCT": "Macrocyte Ratio\n Percentage",
    "MicroR_PCT": "Microcyte Ratio\n Percentage",
    "NE-BF#(10^3/uL)": "Neutrophil\n BF Count",
    "NE-BF%(%)": "Neutrophil\n BF Percentage",
    "NEUT#(hsA)(10^3/uL)": "Neutrophil\n Count (hsA)",
    "NEUT%(hsA)(%)": "Neutrophil\n Percentage (hsA)",
    "NEUT-GI(SI)": "Neutrophil\n GI (Scatter Intensity)",
    "NEUT-RI(FI)": "Neutrophil\n RI (Fluorescence Intensity)",
    "NEUT_PCT": "Neutrophil\n Percentage",
    "NEUTx_10_9_L": "Neutrophil\n Count",
    "NEUTx_PCT": "Neutrophil\n Percentage",
    "NE_FSC_ch": "Neutrophil\n FSC Channel",
    "NE_SFL_ch": "Neutrophil\n SFL Channel",
    "NE_SSC_ch": "Neutrophil\n SSC Channel",
    "NE_WX": "Neutrophil\n WX",
    "NE_WY": "Neutrophil\n WY",
    "NE_WZ": "Neutrophil\n WZ",
    "NRBC-X(ch)": "Nucleated RBC\n X Channel",
    "NRBC-Y(ch)": "Nucleated RBC\n Y Channel",
    "NRBC_10_9_L": "NRBC",
    "NRBC_PCT": "NRBC%",
    "P-MFV(fL)": "Most frequent\n Platelet Volume",
    "PCT_PCT": "Plateletcrit\n Percentage",
    "PDW_fL": "Platelet Distribution\n Width",
    "PLT Abnormal": "Platelet Abnormal",
    "PLT Suspect": "Platelet Suspect",
    "PLT-F-AREA1#()": "PLT-F Area\n 1 Count",
    "PLT-F-RBC-WX()": "PLT-F RBC WX",
    "PLT-F-RBC-WY()": "PLT-F RBC WY",
    "PLT-F-RBC-X(ch)": "PLT-F RBC X\n Channel",
    "PLT-F-RBC-Y(ch)": "PLT-F RBC Y\n Channel",
    "PLT-F-RBC-Z(ch)": "PLT-F RBC Z\n Channel",
    "PLT-F-X(ch)": "PLT-F X Channel",
    "PLT-F-Y(ch)": "PLT-F Y Channel",
    "PLT-F-Z(ch)": "PLT-F Z Channel",
    "PLT-F2(10^3/uL)": "PLT-F Count\n 2",
    "PLT-F_DATA_COUNT_A()": "PLT-F Data\n Count A",
    "PLT-F_PLOT_COUNT_A()": "PLT-F Plot\n Count A",
    "PLT-F_PLOT_COUNT_B()": "PLT-F Plot\n Count B",
    "PLT-F_SIGNAL_COUNT_A()": "PLT-F Signal\n Count A",
    "PLTF_WBC_cov_XX": "PLT-F WBC Covariance\n XX",
    "PLTF_WBC_cov_XY": "PLT-F WBC Covariance\n XY",
    "PLTF_WBC_cov_XZ": "PLT-F WBC Covariance\n XZ",
    "PLTF_WBC_cov_YX": "PLT-F WBC Covariance\n YX",
    "PLTF_WBC_cov_YY": "PLT-F WBC Covariance\n YY",
    "PLTF_WBC_cov_YZ": "PLT-F WBC Covariance\n YZ",
    "PLTF_WBC_cov_ZX": "PLT-F WBC Covariance\n ZX",
    "PLTF_WBC_cov_ZY": "PLT-F WBC Covariance\n ZY",
    "PLTF_WBC_cov_ZZ": "PLT-F WBC Covariance\n ZZ",
    "PLTF_WBC_mean_X": "PLT-F WBC Mean\n X",
    "PLTF_WBC_mean_Y": "PLT-F WBC Mean\n Y",
    "PLTF_WBC_mean_Z": "PLT-F WBC Mean\n Z",
    "PLT_F_10_9_L": "PLT-F",
    "PLT_I_10_9_L": "PLT-I",
    "PLT_O_10_9_L": "PLT-O",
    "PMN#(10^3/uL)": "Polymorphonuclear\n Count",
    "PMN#(hsA)(10^3/uL)": "PMN Count (hsA)",
    "PMN%(%)": "Polymorphonuclear\n Percentage",
    "PMN%(hsA)(%)": "Polymorphonuclear\n Percentage (hsA)",
    "PRBC-WDF#()": "PRBC WDF Count",
    "PRBC-WNR#()": "PRBC WNR Count",
    "P_LCR_PCT": "Platelet Large\n Cell Ratio Percentage",
    "Positive(Count)": "Positive Count",
    "Positive(Diff.)": "Positive Difference",
    "Positive(Morph.)": "Positive Morphology",
    "Q-Flag(Abn Lymho/L-Blasts?)_disc": "Q: Abnormal\n Lymphocytes/Blasts? DISCRETE",
    "Q-Flag(Abn Lymho/L-Blasts?)_err": "Q: Abnormal\n Lymphocytes/Blasts? Error",
    "Q-Flag(AbnLymp?)": "Q: Abnormal\n Lymphocytes?",
    "Q-Flag(AbnLymp?)_disc": "Q: Abnormal\n Lymphocytes? DISCRETE",
    "Q-Flag(AbnLymp?)_err": "Q: Abnormal\n Lymphocytes? Error",
    "Q-Flag(Atypical Lympho?)_disc": "Q: Atypical\n Lymphocytes? DISCRETE",
    "Q-Flag(Atypical Lympho?)_err": "Q: Atypical\n Lymphocytes? Error",
    "Q-Flag(Blasts?)_disc": "Q: Blasts?\n DISCRETE",
    "Q-Flag(Blasts?)_err": "Q: Blasts?\n Error",
    "Q-Flag(Fragments?)_disc": "Q: Fragments?\n DISCRETE",
    "Q-Flag(Fragments?)_err": "Q: Fragments?\n Error",
    "Q-Flag(Giant PLT?)_disc": "Q: Giant Platelets?\n DISCRETE",
    "Q-Flag(Giant PLT?)_err": "Q: Giant Platelets?\n Error",
    "Q-Flag(HGB Defect?)_disc": "Q: Haemoglobin\n Defect? DISCRETE",
    "Q-Flag(HGB Defect?)_err": "Q: Haemoglobin\n Defect? Error",
    "Q-Flag(Iron Deficiency?)_disc": "Q: Iron Deficiency?\n DISCRETE",
    "Q-Flag(Iron Deficiency?)_err": "Q: Iron Deficiency?\n Error",
    "Q-Flag(Left Shift?)_disc": "Q: Left Shift?\n DISCRETE",
    "Q-Flag(Left Shift?)_err": "Q: Left Shift?\n Error",
    "Q-Flag(PLT Clumps?)_disc": "Q: Platelet\n Clumps? DISCRETE",
    "Q-Flag(PLT Clumps?)_err": "Q: Platelet\n Clumps? Error",
    "Q-Flag(RBC Agglutination?)_disc": "Q: RBC Agglutination?\n DISCRETE",
    "Q-Flag(RBC Agglutination?)_err": "Q: RBC Agglutination?\n Error",
    "Q-Flag(Turbidity/HGB Interf?)_disc": "Q: Turbidity/Haemoglobin\n Interference? DISCRETE",
    "Q-Flag(Turbidity/HGB Interf?)_err": "Q: Turbidity/Haemoglobin\n Interference? Error",
    "Q-Flag(pRBC?(R))": "Q: Pathological\n RBC (Reticulocyte)?",
    "Q-Flag(pRBC?(R))_disc": "Q: Pathological\n RBC (Reticulocyte)? DISCRETE",
    "Q-Flag(pRBC?(R))_err": "Q: Pathological\n RBC (Reticulocyte)? Error",
    "Q-Flag(pRBC?)_disc": "Q: Pathological\n RBC? DISCRETE",
    "Q-Flag(pRBC?)_err": "Q: Pathological\n RBC? Error",
    "R-MFV(fL)": "Most frequent\n RBC Volume",
    "RBC Abnormal": "RBC Abnormal",
    "RBC Suspect": "RBC Suspect",
    "RBC(hsA)(10^6/uL)": "RBC Count (hsA)",
    "RBC-BF(10^6/uL)": "RBC BF Count",
    "RBC-BF-I(10^6/uL)": "RBC BF-I Count",
    "RBC-BF2(10^6/uL)": "RBC BF2 Count",
    "RBC-I(10^6/uL)": "RBC-I Count",
    "RBC-I(hsA)(10^6/uL)": "RBC-I Count\n (hsA)",
    "RBC-O(hsA)(10^6/uL)": "RBC-O Count\n (hsA)",
    "RBC_10_12_L": "RBC",
    "RBC_O_10_12_L": "RBC-O",
    "RE-LYMP#(10^3/uL)": "Reactive Lymphocyte\n Count",
    "RE-LYMP%(%)": "Reactive Lymphocyte\n Percentage",
    "RE-LYMP%L(%)": "Reactive Lymphocyte\n Large Percentage",
    "RET-RBC-WX()": "RET RBC WX",
    "RET-RBC-WY()": "RET RBC WY",
    "RET-RBC-X(ch)": "RET RBC X Channel",
    "RET-RBC-Z(ch)": "RET RBC Z Channel",
    "RET-X(ch)": "Reticulocyte\n X Channel",
    "RET_10_6_uL": "Reticulocyte\n Count",
    "RET_He_pg": "Reticulocyte\n Haemoglobin Equivalent",
    "RET_PCT": "Reticulocyte\n Percentage",
    "RET_PLT_cov_XX": "RET Platelet\n Covariance XX",
    "RET_PLT_cov_XY": "RET Platelet\n Covariance XY",
    "RET_PLT_cov_YX": "RET Platelet\n Covariance YX",
    "RET_PLT_cov_YY": "RET Platelet\n Covariance YY",
    "RET_PLT_mean_X": "RET Platelet\n Mean X",
    "RET_PLT_mean_Y": "RET Platelet\n Mean Y",
    "RET_RBC_Y_ch": "RET RBC Y Channel",
    "RET_RET_cov_XX": "RET Reticulocyte\n Covariance XX",
    "RET_RET_cov_XY": "RET Reticulocyte\n Covariance XY",
    "RET_RET_cov_YX": "RET Reticulocyte\n Covariance YX",
    "RET_RET_cov_YY": "RET Reticulocyte\n Covariance YY",
    "RET_RET_mean_X": "RET Reticulocyte\n Mean X",
    "RET_RET_mean_Y": "RET Reticulocyte\n Mean Y",
    "RET_TNC": "RET Total Nucleated\n Cell Count",
    "RET_TOTAL_COUNT()": "Reticulocyte\n Total Count",
    "RET_UPP": "RET Upper Fraction",
    "RET_Y_ch": "Reticulocyte\n Y Channel",
    "S-MCV(fL)": "MCV of the\n smaller RBC dist.",
    "S-RBC(10^6/uL)": "RBC Count of\n the smaller RBC dist.",
    "TC#(hsA)(10^3/uL)": "Total Count\n (hsA)",
    "TC-BF#(10^3/uL)": "Total BF Count",
    "TNC-D2(10^3/uL)": "TNC-D2",
    "TNC-N2(10^3/uL)": "TNC-N2",
    "TNC-P(10^3/uL)": "TNC-P",
    "TNC-P2(10^3/uL)": "TNC-P2",
    "TNC_D_10_9_L": "TNC-D Count",
    "TNC_N_10_9_L": "TNC-N Count",
    "WBC Abnormal": "WBC Abnormal",
    "WBC Suspect": "WBC Suspect",
    "WBC(hsA)(10^3/uL)": "WBC Count (hsA)",
    "WBC-BF(10^3/uL)": "WBC BF Count",
    "WBC-D2(10^3/uL)": "WBC Differential\n Count 2",
    "WBC-FX(ch)": "WBC FX Channel",
    "WBC-N(SSC-FSC)(10^3/uL)": "WBC N SSC-FSC\n Count",
    "WBC-N(SSC-FSC)2(10^3/uL)": "WBC N SSC-FSC\n Count 2",
    "WBC-N2(10^3/uL)": "WBC N Count\n 2",
    "WBC-P(10^3/uL)": "WBC P Count",
    "WBC-P2(10^3/uL)": "WBC P Count\n 2",
    "WBC_D_10_9_L": "WBC Count",
    "WBC_N_10_9_L": "WBC Nucleated\n Cell Count",
    "WDF-WX()": "WDF WX",
    "WDF-WY()": "WDF WY",
    "WDF-X(ch)": "WDF X Channel",
    "WDF-Y(ch)": "WDF Y Channel",
    "WDF-Z(ch)": "WDF Z Channel",
    "WDF_PLOT_COUNT()": "WDF Plot Count",
    "WDF_TOTAL_COUNT()": "WDF Total Count",
    "WNR-WX()": "WNR WX",
    "WNR-WY()": "WNR WY",
    "WNR-X(ch)": "WNR X Channel",
    "WNR-Y(ch)": "WNR Y Channel",
    "WNR-Z(ch)": "WNR Z Channel",
    "WNR_TOTAL_COUNT()": "WNR Total Count",
    "WPC-AREA1#()": "WPC Area 1\n Count",
    "WPC-AREA2#()": "WPC Area 2\n Count",
    "WPC-AREA3#()": "WPC Area 3\n Count",
    "WPC-X(ch)": "WPC X Channel",
    "WPC-Y(ch)": "WPC Y Channel",
    "WPC-Z(ch)": "WPC Z Channel",
    "WPC_PLOT_COUNT()": "WPC Plot Count",
    "WPC_TOTAL_COUNT()": "WPC Total Count",
    "HGB_g_L": "HGB",
    "raw_RBC_embed_0": "Impedance Embedding\n Feature 0",
    "raw_RBC_embed_1": "Impedance Embedding\n Feature 1",
    "raw_RBC_embed_2": "Impedance Embedding\n Feature 2",
    "raw_RBC_embed_3": "Impedance Embedding\n Feature 3",
    "raw_RBC_embed_4": "Impedance Embedding\n Feature 4",
    "raw_RBC_embed_5": "Impedance Embedding\n Feature 5",
    "raw_RBC_embed_6": "Impedance Embedding\n Feature 6",
    "raw_RBC_embed_7": "Impedance Embedding\n Feature 7",
    "raw_RBC_reconloss": "Impedance Reconstruction\n Loss",
    "MCV_fL": "MCV",
    "MCH_pg": "MCH",
    "MCHC_g_dL": "MCHC",
    "PLT_10_9_L": "PLT",
    "NEUT_10_9_L": "NEUT",
    "LYMPH_10_9_L": "LYMPH",
    "RDW_SD_fL": "RDW-SD",
    "RDW_CV_PCT": "RDW",
    "RBC_He_pg": "RBC Haemoglobin\n Equivalent",
    "PLTF_PLT_cov_XX": "PLT-F Platelet\n Covariance XX",
    "PLTF_PLT_cov_XY": "PLT-F Platelet\n Covariance XY",
    "PLTF_PLT_cov_XZ": "PLT-F Platelet\n Covariance XZ",
    "PLTF_PLT_cov_YX": "PLT-F Platelet\n Covariance YX",
    "PLTF_PLT_cov_YY": "PLT-F Platelet\n Covariance YY",
    "PLTF_PLT_cov_YZ": "PLT-F Platelet\n Covariance YZ",
    "PLTF_PLT_cov_ZX": "PLT-F Platelet\n Covariance ZX",
    "PLTF_PLT_cov_ZY": "PLT-F Platelet\n Covariance ZY",
    "PLTF_PLT_cov_ZZ": "PLT-F Platelet\n Covariance ZZ",
    "PLTF_PLT_mean_X": "PLT-F Platelet\n Mean X",
    "PLTF_PLT_mean_Y": "PLT-F Platelet\n Mean Y",
    "PLTF_PLT_mean_Z": "PLT-F Platelet\n Mean Z",
    "PLTF_RBC_cov_XX": "PLT-F RBC Covariance\n XX",
    "PLTF_RBC_cov_XY": "PLT-F RBC Covariance\n XY",
    "PLTF_RBC_cov_XZ": "PLT-F RBC Covariance\n XZ",
    "PLTF_RBC_cov_YX": "PLT-F RBC Covariance\n YX",
    "PLTF_RBC_cov_YY": "PLT-F RBC Covariance\n YY",
    "PLTF_RBC_cov_YZ": "PLT-F RBC Covariance\n YZ",
    "PLTF_RBC_cov_ZX": "PLT-F RBC Covariance\n ZX",
    "PLTF_RBC_cov_ZY": "PLT-F RBC Covariance\n ZY",
    "PLTF_RBC_cov_ZZ": "PLT-F RBC Covariance\n ZZ",
    "PLTF_RBC_mean_X": "PLT-F RBC Mean\n X",
    "PLTF_RBC_mean_Y": "PLT-F RBC Mean\n Y",
    "PLTF_RBC_mean_Z": "PLT-F RBC Mean\n Z",
    "RET_RBC_cov_XX": "RET RBC Covariance\n XX",
    "RET_RBC_cov_XY": "RET RBC Covariance\n XY",
    "RET_RBC_cov_YX": "RET RBC Covariance\n YX",
    "RET_RBC_cov_YY": "RET RBC Covariance\n YY",
    "RET_RBC_mean_X": "RET RBC Mean\n X",
    "RET_RBC_mean_Y": "RET RBC Mean\n Y",
    "RET_TOTAL_COUNT": "RET Total Count",
    "RPI": "Reticulocyte\n Production Index",
    "S-MCV_fL": "MCV of smaller\n RBC dist.",
    "S-RBC_10_6_uL": "RBC of smaller\n RBC dist.",
    "TNC_10_9_L": "Total Nucleated\n Cell Count",
    "WBC_10_9_L": "WBC",
    "WDF-X": "WDF Lateral\n Scattered Light Intensity",
    "WDF-Y": "WDF Fluorescent\n Light Intensity",
    "WDF-Z": "WDF Forward\n Scattered Light Intensity",
    "WPC-X": "WPC Lateral\n Scattered Light Intensity",
    "WPC-Y": "WPC Fluorescent\n Light Intensity",
    "WPC-Z": "WPC Forward\n Scattered Light Intensity",
    "IP ABN(PLT)PLT Abn Distribution": "IP: PLT Abnormal\n Distribution",
    "IP ABN(PLT)PLT Abn Scattergram": "IP: PLT Abnormal\n Scattergram",
    "IP ABN(PLT)Thrombocytopenia": "IP: Thrombocytopenia",
    "IP ABN(PLT)Thrombocytosis": "IP: Thrombocytosis",
    "IP ABN(RBC)Anemia": "IP: Anaemia",
    "IP ABN(RBC)Anisocytosis": "IP: Anisocytosis",
    "IP ABN(RBC)Dimorphic Population": "IP: Dimorphic\n Population",
    "IP ABN(RBC)Erythrocytosis": "IP: Erythrocytosis",
    "IP ABN(RBC)Hypochromia": "IP: Hypochromia",
    "IP ABN(RBC)Macrocytosis": "IP: Macrocytosis",
    "IP ABN(RBC)Microcytosis": "IP: Microcytosis",
    "IP ABN(RBC)RBC Abn Distribution": "IP: RBC Abnormal\n Distribution",
    "IP ABN(RBC)RET Abn Scattergram": "IP: RET Abnormal\n Scattergram",
    "IP ABN(RBC)Reticulocytosis": "IP: Reticulocytosis",
    "IP ABN(WBC)Basophilia": "IP: Basophilia",
    "IP ABN(WBC)Eosinophilia": "IP: Eosinophilia",
    "IP ABN(WBC)IG Present": "IP: Immature\n Granulocytes Present",
    "IP ABN(WBC)Leukocytopenia": "IP: Leukocytopenia",
    "IP ABN(WBC)Leukocytosis": "IP: Leukocytosis",
    "IP ABN(WBC)Lympocytosis": "IP: Lymphocytosis",
    "IP ABN(WBC)Lympopenia": "IP: Lymphopenia",
    "IP ABN(WBC)Monocytosis": "IP: Monocytosis",
    "IP ABN(WBC)NRBC Present": "IP: Nucleated\n RBC Present",
    "IP ABN(WBC)Neutoropenia": "IP: Neutropenia",
    "IP ABN(WBC)Neutorophilia": "IP: Neutrophilia",
    "IP ABN(WBC)WBC Abn Scattergram": "IP: WBC Abnormal\n Scattergram",
    "Q-Flag(Abn Lymho/L-Blasts?)": "Q: Abnormal\n Lymphocytes/Blasts?",
    "Q-Flag(Atypical Lympho?)": "Q: Atypical\n Lymphocytes?",
    "Q-Flag(Blasts?)": "Q: Blasts?",
    "Q-Flag(Faulty HGB?)": "Q: Faulty Haemoglobin?",
    "Q-Flag(Fragments?)": "Q: Fragments?",
    "Q-Flag(Giant PLT?)": "Q: Giant Platelets?",
    "Q-Flag(HGB Defect?)": "Q: Haemoglobin\n Defect?",
    "Q-Flag(Iron Deficiency?)": "Q: Iron Deficiency?",
    "Q-Flag(Left Shift?)": "Q: Left Shift?",
    "Q-Flag(PLT Clumps?)": "Q: Platelet\n Clumps?",
    "Q-Flag(RBC Agglutination?)": "Q: RBC Agglutination?",
    "Q-Flag(Turbidity/HGB Interf?)": "Q: Turbidity/Haemoglobin\n Interference?",
    "Q-Flag(pRBC?)": "Q: pRBC?",
    "FERR": "Ferritin",
    "CRP": "C-Reactive\n Protein",
    "subject_trial_arm": "Trial Arm",
    "subject_trial_arm_severity": "Trial Arm Severity",
    "IPF#_linearity": "IPF lin.",
    "HF%(hsA)_linearity": "High Fluorescence\n Lymphocyte Percentage (hsA) lin.",
    "RPI_unreliable": "Reticulocyte\n Production Index unr.",
    "LYMP#&_linearity": "Lymphocyte\n Count lin.",
    "EO-BF#_linearity": "Eosinophil\n BF Count lin.",
    "IG%_unreliable": "Immature Granulocytes\n Percentage unr.",
    "H-IPF_unreliable": "H-IPF unr.",
    "HF-BF%_linearity": "HF-BF Percentage\n lin.",
    "H-IPF_linearity": "H-IPF lin.",
    "HFLC%_linearity": "HFLC Percentage\n lin.",
    "HFLC%_unreliable": "HFLC Percentage\n unr.",
    "PDW_linearity": "Platelet Distribution\n Width lin.",
    "PLT_unreliable": "Platelet unr.",
    "RE-LYMP%_unreliable": "Reactive Lymphocyte\n Percentage unr.",
    "RET-He_unreliable": "Reticulocyte\n Haemoglobin unr.",
    "NEUT%_linearity": "Neutrophil\n Percentage lin.",
    "NE-BF%_unreliable": "NE-BF Percentage\n unr.",
    "NEUT%&_linearity": "Neutrophil\n Percentage lin.",
    "EO%_linearity": "Eosinophil\n Percentage lin.",
    "NEUT#_unreliable": "Neutrophil\n Count unr.",
    "HGB-O_linearity": "HGB-O lin.",
    "RET-UPP_unreliable": "RET-UPP unr.",
    "MCV_linearity": "Mean Corpuscular\n Volume lin.",
    "RE-LYMP%_linearity": "Reactive Lymphocyte\n Percentage lin.",
    "BA-N#_linearity": "BA-N Count\n lin.",
    "RBC-He_linearity": "RBC Haemoglobin\n lin.",
    "NRBC%_linearity": "NRBC Percentage\n lin.",
    "NEUT-GI_linearity": "Neutrophil\n GI lin.",
    "LY-Z_linearity": "Lymphocyte\n Z lin.",
    "MicroR_linearity": "Microcyte Ratio\n lin.",
    "LY-BF%_linearity": "LY-BF Percentage\n lin.",
    "P-LCR_unreliable": "Platelet Large\n Cell Ratio unr.",
    "RET#_unreliable": "Reticulocyte\n Count unr.",
    "EO%(hsA)_linearity": "Eosinophil\n Percentage (hsA) lin.",
    "RBC(hsA)_linearity": "RBC Count (hsA)\n lin.",
    "EO%_unreliable": "Eosinophil\n Percentage unr.",
    "MO-X_unreliable": "Monocyte X\n unr.",
    "PDW_unreliable": "Platelet Distribution\n Width unr.",
    "PMN#_unreliable": "Polymorphonuclear\n Count unr.",
    "BA-D%_linearity": "BA-D Percentage\n lin.",
    "HPC#_linearity": "HPC Count lin.",
    "PLT-O_unreliable": "PLT-O unr.",
    "HF#(hsA)_linearity": "High Fluorescence\n Lymphocyte Count (hsA) lin.",
    "WBC-N(SSC-FSC)_unreliable": "WBC N SSC-FSC\n Count unr.",
    "HCT_linearity": "Haematocrit\n lin.",
    "MO-WZ_unreliable": "Monocyte WZ\n unr.",
    "WBC-N(SSC-FSC)2_unreliable": "WBC N SSC-FSC\n Count 2 unr.",
    "LYMP%&_linearity": "Lymphocyte\n Percentage lin.",
    "Delta-He_linearity": "Delta He lin.",
    "TC#(hsA)_linearity": "Total Count\n (hsA) lin.",
    "NE-WX_unreliable": "Neutrophil\n WX unr.",
    "RE-LYMP#_unreliable": "Reactive Lymphocyte\n Count unr.",
    "BASO%_linearity": "BASO Percentage\n lin.",
    "BASO#_linearity": "BASO Count\n lin.",
    "LY-Z_unreliable": "Lymphocyte\n Z unr.",
    "WBC-BF_unreliable": "WBC BF Count\n unr.",
    "WBC-P_unreliable": "WBC P unr.",
    "AS-LYMP#_linearity": "AS Lymphocyte\n Count lin.",
    "RET-Y_linearity": "Reticulocyte\n Y lin.",
    "IPF_unreliable": "IPF unr.",
    "HYPER-He_unreliable": "Hyper-He unr.",
    "PMN%_unreliable": "PMN Percentage\n unr.",
    "TC-BF#_unreliable": "Total BF Count\n unr.",
    "BA-D#_linearity": "BA-D Count\n lin.",
    "MPV_linearity": "Mean Platelet\n Volume lin.",
    "RBC-BF_linearity": "RBC BF Count\n lin.",
    "HF%(hsA)_unreliable": "High Fluorescence\n Lymphocyte Percentage (hsA) unr.",
    "HGB_linearity": "HGB lin.",
    "P-LCR_linearity": "Platelet Large\n Cell Ratio lin.",
    "MONO%_linearity": "Monocyte Percentage\n lin.",
    "AS-LYMP%_linearity": "AS Lymphocyte\n Percentage lin.",
    "LY-BF#_linearity": "LY-BF Count\n lin.",
    "WBC_linearity": "WBC lin.",
    "RBC-I(hsA)_unreliable": "RBC-I (hsA)\n unr.",
    "WBC_unreliable": "WBC unr.",
    "WBC-BF_linearity": "WBC BF Count\n lin.",
    "LYMP%&_unreliable": "Lymphocyte\n Percentage unr.",
    "MO-Z_unreliable": "Monocyte Z\n unr.",
    "LYMPH%(hsA)_linearity": "Lymphocyte\n Percentage (hsA) lin.",
    "PLT-F2_unreliable": "PLT-F Count\n 2 unr.",
    "MCH_linearity": "Mean Corpuscular\n Haemoglobin lin.",
    "FRC#_unreliable": "FRC Count unr.",
    "EO-BF%_linearity": "Eosinophil\n BF Percentage lin.",
    "HGB-O_unreliable": "HGB-O unr.",
    "LY-BF%_unreliable": "LY-BF Percentage\n unr.",
    "LY-Y_unreliable": "Lymphocyte\n Y unr.",
    "HF-BF#_unreliable": "HF-BF Count\n unr.",
    "LYMPH#(hsA)_unreliable": "Lymphocyte\n Count (hsA) unr.",
    "HFLC#_unreliable": "HFLC Count\n unr.",
    "TNC_linearity": "TNC lin.",
    "MPV_unreliable": "Mean Platelet\n Volume unr.",
    "LYMPH#_unreliable": "Lymphocyte\n Count unr.",
    "WBC(hsA)_linearity": "WBC (hsA) lin.",
    "BASO#_unreliable": "BASO Count\n unr.",
    "TNC-P_linearity": "TNC-P lin.",
    "LY-Y_linearity": "Lymphocyte\n Y lin.",
    "RPI_linearity": "Reticulocyte\n Production Index lin.",
    "NEUT-GI_unreliable": "Neutrophil\n GI unr.",
    "RET-RBC-Y_linearity": "RET-RBC Y lin.",
    "NE-FSC_linearity": "Neutrophil\n FSC lin.",
    "LY-WY_linearity": "Lymphocyte\n WY lin.",
    "LY-WZ_unreliable": "Lymphocyte\n WZ unr.",
    "MONO#(hsA)_unreliable": "Monocyte Count\n (hsA) unr.",
    "MONO%(hsA)_unreliable": "Monocyte Percentage\n (hsA) unr.",
    "WBC(hsA)_unreliable": "WBC (hsA) unr.",
    "RET-He_linearity": "Reticulocyte\n Haemoglobin lin.",
    "TC-BF#_linearity": "Total BF Count\n lin.",
    "PMN#_linearity": "Polymorphonuclear\n Count lin.",
    "EO#(hsA)_unreliable": "Eosinophil\n Count (hsA) unr.",
    "MN#(hsA)_unreliable": "Monocyte Count\n (hsA) unr.",
    "RDW-SD_linearity": "RDW-SD lin.",
    "TNC_unreliable": "TNC unr.",
    "IG#_linearity": "Immature Granulocytes\n Count lin.",
    "MO-Y_linearity": "Monocyte Y\n lin.",
    "MN#_unreliable": "Monocyte Count\n unr.",
    "IPF_linearity": "IPF lin.",
    "IRF-Y_linearity": "Immature Reticulocyte\n Fraction lin.",
    "MO-WY_unreliable": "Monocyte WY\n unr.",
    "HGB-S_unreliable": "HGB-S unr.",
    "TNC-D_linearity": "TNC-D lin.",
    "WBC-N(SSC-FSC)2_linearity": "WBC N SSC-FSC\n Count 2 lin.",
    "BA-D%_unreliable": "BA-D Percentage\n unr.",
    "LFR_linearity": "Low Fluorescence\n Ratio lin.",
    "RBC-O(hsA)_unreliable": "RBC-O (hsA)\n unr.",
    "EO%(hsA)_unreliable": "Eosinophil\n Percentage (hsA) unr.",
    "EO-BF#_unreliable": "Eosinophil\n BF Count unr.",
    "MacroR_unreliable": "Macrocyte Ratio\n unr.",
    "MO-Y_unreliable": "Monocyte Y\n unr.",
    "MO-BF#_unreliable": "MO-BF Count\n unr.",
    "RBC-I(hsA)_linearity": "RBC-I (hsA)\n lin.",
    "PLT-F_unreliable": "PLT-F unr.",
    "NEUT-RI_unreliable": "Neutrophil\n RI unr.",
    "WBC-N_unreliable": "WBC N unr.",
    "PMN#(hsA)_linearity": "Polymorphonuclear\n Count (hsA) lin.",
    "MONO#(hsA)_linearity": "Monocyte Count\n (hsA) lin.",
    "MO-WX_linearity": "Monocyte WX\n lin.",
    "MN%(hsA)_unreliable": "Monocyte Percentage\n (hsA) unr.",
    "EO#_linearity": "Eosinophil\n Count lin.",
    "RBC-O_linearity": "RBC-O Count\n lin.",
    "NE-SFL_unreliable": "Neutrophil\n SFL unr.",
    "LY-BF#_unreliable": "LY-BF Count\n unr.",
    "IRF-Y_unreliable": "Immature Reticulocyte\n Fraction unr.",
    "NE-WY_linearity": "Neutrophil\n WY lin.",
    "MCHC_linearity": "Mean Corpuscular\n Haemoglobin Concentration lin.",
    "LYMPH%(hsA)_unreliable": "Lymphocyte\n Percentage (hsA) unr.",
    "RE-LYMP#_linearity": "Reactive Lymphocyte\n Count lin.",
    "Delta-He_unreliable": "Delta He unr.",
    "RET-RBC-Y_unreliable": "RET-RBC Y unr.",
    "HF-BF%_unreliable": "HF-BF Percentage\n unr.",
    "NEUT#(hsA)_unreliable": "Neutrophil\n Count (hsA) unr.",
    "LYMPH%_unreliable": "Lymphocyte\n Percentage unr.",
    "MO-WZ_linearity": "Monocyte WZ\n lin.",
    "PLT-I_unreliable": "PLT-I unr.",
    "HFR_linearity": "High Fluorescence\n Reticulocyte lin.",
    "HGB_unreliable": "HGB unr.",
    "MO-Z_linearity": "Monocyte Z\n lin.",
    "HFLC#_linearity": "HFLC Count\n lin.",
    "LFR_unreliable": "Low Fluorescence\n Ratio unr.",
    "BA-N%_linearity": "BA-N Percentage\n lin.",
    "LY-WX_unreliable": "Lymphocyte\n WX unr.",
    "MCH_unreliable": "Mean Corpuscular\n Haemoglobin unr.",
    "EO-BF%_unreliable": "Eosinophil\n BF Percentage unr.",
    "RET%_linearity": "Reticulocyte\n Percentage lin.",
    "LYMP#&_unreliable": "Lymphocyte\n Count unr.",
    "PLT-F2_linearity": "PLT-F Count\n 2 lin.",
    "NEUT%_unreliable": "Neutrophil\n Percentage unr.",
    "NE-WY_unreliable": "Neutrophil\n WY unr.",
    "TNC-D_unreliable": "TNC-D unr.",
    "HYPO-He_unreliable": "HYPO-He unr.",
    "MONO%_unreliable": "Monocyte Percentage\n unr.",
    "PLT-F_linearity": "PLT-F lin.",
    "MN%(hsA)_linearity": "Monocyte Percentage\n (hsA) lin.",
    "RBC-I_unreliable": "RBC-I Count\n unr.",
    "LYMPH#_linearity": "Lymphocyte\n Count lin.",
    "NRBC#_linearity": "NRBC Count\n lin.",
    "RBC-BF2_unreliable": "RBC BF2 Count\n unr.",
    "RET-UPP_linearity": "RET-UPP lin.",
    "MCHC_unreliable": "Mean Corpuscular\n Haemoglobin Concentration unr.",
    "RBC-O(hsA)_linearity": "RBC-O (hsA)\n lin.",
    "NEUT%&_unreliable": "Neutrophil\n Percentage unr.",
    "FRC#_linearity": "FRC Count lin.",
    "MO-BF%_unreliable": "MO-BF Percentage\n unr.",
    "NE-WZ_linearity": "Neutrophil\n WZ lin.",
    "AS-LYMP%_unreliable": "AS Lymphocyte\n Percentage unr.",
    "MFR_unreliable": "Mid Fluorescence\n Ratio unr.",
    "MicroR_unreliable": "Microcyte Ratio\n unr.",
    "LY-WY_unreliable": "Lymphocyte\n WY unr.",
    "BA-N#_unreliable": "BA-N Count\n unr.",
    "NEUT#&_unreliable": "Neutrophil\n Count unr.",
    "RBC-I_linearity": "RBC-I Count\n lin.",
    "MONO%(hsA)_linearity": "Monocyte Percentage\n (hsA) lin.",
    "TNC-N_linearity": "TNC-N lin.",
    "RBC-BF_unreliable": "RBC BF Count\n unr.",
    "PMN#(hsA)_unreliable": "Polymorphonuclear\n Count (hsA) unr.",
    "BASO%_unreliable": "BASO Percentage\n unr.",
    "AS-LYMP%L_linearity": "AS Lymphocyte\n Large Percentage lin.",
    "NE-SSC_unreliable": "Neutrophil\n SSC unr.",
    "LY-WZ_linearity": "Lymphocyte\n WZ lin.",
    "BA-D#_unreliable": "BA-D Count\n unr.",
    "RET%_unreliable": "Reticulocyte\n Percentage unr.",
    "NE-WX_linearity": "Neutrophil\n WX lin.",
    "NE-SFL_linearity": "Neutrophil\n SFL lin.",
    "HYPO-He_linearity": "HYPO-He lin.",
    "NEUT#(hsA)_linearity": "Neutrophil\n Count (hsA) lin.",
    "LY-X_unreliable": "Lymphocyte\n X unr.",
    "RDW-CV_linearity": "RDW-CV lin.",
    "RET-TNC_linearity": "RET-TNC lin.",
    "WBC-D_linearity": "WBC Differential\n lin.",
    "LY-X_linearity": "Lymphocyte\n X lin.",
    "PLT_linearity": "Platelet lin.",
    "PCT_linearity": "Plateletcrit\n lin.",
    "MO-X_linearity": "Monocyte X\n lin.",
    "MO-WX_unreliable": "Monocyte WX\n unr.",
    "LYMPH%_linearity": "Lymphocyte\n Percentage lin.",
    "MacroR_linearity": "Macrocyte Ratio\n lin.",
    "NE-BF#_linearity": "NE-BF Count\n lin.",
    "MN%_linearity": "Monocyte Percentage\n lin.",
    "WBC-N_linearity": "WBC N lin.",
    "LYMPH#(hsA)_linearity": "Lymphocyte\n Count (hsA) lin.",
    "FRC%_unreliable": "FRC Percentage\n unr.",
    "NE-FSC_unreliable": "Neutrophil\n FSC unr.",
    "NE-BF#_unreliable": "NE-BF Count\n unr.",
    "BA-N%_unreliable": "BA-N Percentage\n unr.",
    "LY-WX_linearity": "Lymphocyte\n WX lin.",
    "WBC-D_unreliable": "WBC Differential\n unr.",
    "IRF_linearity": "Immature Reticulocyte\n Fraction lin.",
    "NEUT#&_linearity": "Neutrophil\n Count lin.",
    "IPF#_unreliable": "IPF unr.",
    "PCT_unreliable": "Plateletcrit\n unr.",
    "MN#(hsA)_linearity": "Monocyte Count\n (hsA) lin.",
    "WBC-N(SSC-FSC)_linearity": "WBC N SSC-FSC\n Count lin.",
    "RDW-SD_unreliable": "RDW-SD unr.",
    "RDW-CV_unreliable": "RDW-CV unr.",
    "EO#(hsA)_linearity": "Eosinophil\n Count (hsA) lin.",
    "HPC#_unreliable": "HPC Count unr.",
    "IRF_unreliable": "Immature Reticulocyte\n Fraction unr.",
    "PLT-I_linearity": "PLT-I lin.",
    "NE-SSC_linearity": "Neutrophil\n SSC lin.",
    "PMN%(hsA)_unreliable": "Polymorphonuclear\n Percentage (hsA) unr.",
    "IG#_unreliable": "Immature Granulocytes\n Count unr.",
    "HYPER-He_linearity": "Hyper-He lin.",
    "EO#_unreliable": "Eosinophil\n Count unr.",
    "MFR_linearity": "Mid Fluorescence\n Ratio lin.",
    "AS-LYMP#_unreliable": "AS Lymphocyte\n Count unr.",
    "RBC-O_unreliable": "RBC-O Count\n unr.",
    "NE-BF%_linearity": "NE-BF Percentage\n lin.",
    "NEUT%(hsA)_linearity": "Neutrophil\n Percentage (hsA) lin.",
    "NEUT#_linearity": "Neutrophil\n Count lin.",
    "MCV_unreliable": "Mean Corpuscular\n Volume unr.",
    "RBC-BF2_linearity": "RBC BF2 Count\n lin.",
    "NRBC%_unreliable": "NRBC Percentage\n unr.",
    "PMN%_linearity": "PMN Percentage\n lin.",
    "RET#_linearity": "Reticulocyte\n Count lin.",
    "RET-Y_unreliable": "Reticulocyte\n Y unr.",
    "WBC-P_linearity": "WBC P lin.",
    "RE-LYMP%L_unreliable": "Reactive Lymphocyte\n Large Percentage unr.",
    "TNC-N_unreliable": "TNC-N unr.",
    "MO-WY_linearity": "Monocyte WY\n lin.",
    "HF#(hsA)_unreliable": "High Fluorescence\n Lymphocyte Count (hsA) unr.",
    "RE-LYMP%L_linearity": "Reactive Lymphocyte\n Large Percentage lin.",
    "RET-TNC_unreliable": "RET-TNC unr.",
    "PLT-O_linearity": "PLT-O lin.",
    "RBC_linearity": "RBC Count lin.",
    "MO-BF#_linearity": "MO-BF Count\n lin.",
    "HF-BF#_linearity": "HF-BF Count\n lin.",
    "PMN%(hsA)_linearity": "Polymorphonuclear\n Percentage (hsA) lin.",
    "NEUT-RI_linearity": "Neutrophil\n RI lin.",
    "MONO#_linearity": "Monocyte Count\n lin.",
    "NEUT%(hsA)_unreliable": "Neutrophil\n Percentage (hsA) unr.",
    "RBC-He_unreliable": "RBC Haemoglobin\n unr.",
    "TC#(hsA)_unreliable": "Total Count\n (hsA) unr.",
    "FRC%_linearity": "FRC Percentage\n lin.",
    "MN#_linearity": "Monocyte Count\n lin.",
    "MN%_unreliable": "Monocyte Percentage\n unr.",
    "HFR_unreliable": "High Fluorescence\n Reticulocyte unr.",
    "NRBC#_unreliable": "NRBC Count\n unr.",
    "AS-LYMP%L_unreliable": "AS Lymphocyte\n Large Percentage unr.",
    "HCT_unreliable": "Haematocrit\n unr.",
    "IG%_linearity": "Immature Granulocytes\n Percentage lin.",
    "MO-BF%_linearity": "MO-BF Percentage\n lin.",
    "RBC_unreliable": "RBC Count unr.",
    "MONO#_unreliable": "Monocyte Count\n unr.",
    "RBC(hsA)_unreliable": "RBC Count (hsA)\n unr.",
    "TNC-P_unreliable": "TNC-P unr.",
    "HGB-S_linearity": "HGB-S lin.",
    "NE-WZ_unreliable": "Neutrophil\n WZ unr.",
    "RET_RBC_mean_SFL": "RET RBC\nmean SFL",
    "RET_RBC_mean_FSC": "RET RBC\nmean FSC",
    "RET_RBC_cov_SFL_SFL": "RET RBC\ncov SFL SFL",
    "RET_RBC_cov_SFL_FSC": "RET RBC\ncov SFL FSC",
    "RET_RBC_cov_FSC_FSC": "RET RBC\ncov FSC FSC",
    "RET_RET_mean_SFL": "RET RET\nmean SFL",
    "RET_RET_mean_FSC": "RET RET\nmean FSC",
    "RET_RET_cov_SFL_SFL": "RET RET\ncov SFL SFL",
    "RET_RET_cov_SFL_FSC": "RET RET\ncov SFL FSC",
    "RET_RET_cov_FSC_FSC": "RET RET\ncov FSC FSC",
    "RET_PLT_mean_SFL": "RET PLT\nmean SFL",
    "RET_PLT_mean_FSC": "RET PLT\nmean FSC",
    "RET_PLT_cov_SFL_SFL": "RET PLT\ncov SFL SFL",
    "RET_PLT_cov_SFL_FSC": "RET PLT\ncov SFL FSC",
    "RET_PLT_cov_FSC_FSC": "RET PLT\ncov FSC FSC",
    "PLTF_RBC_mean_SFL": "PLTF RBC\nmean SFL",
    "PLTF_RBC_mean_FSC": "PLTF RBC\nmean FSC",
    "PLTF_RBC_mean_SSC": "PLTF RBC\nmean SSC",
    "PLTF_RBC_mean_FSCW": "PLTF RBC\nmean FSCW",
    "PLTF_RBC_cov_SFL_SFL": "PLTF RBC\ncov SFL SFL",
    "PLTF_RBC_cov_SFL_FSC": "PLTF RBC\ncov SFL FSC",
    "PLTF_RBC_cov_SFL_SSC": "PLTF RBC\ncov SFL SSC",
    "PLTF_RBC_cov_SFL_FSCW": "PLTF RBC\ncov SFL FSCW",
    "PLTF_RBC_cov_FSC_FSC": "PLTF RBC\ncov FSC FSC",
    "PLTF_RBC_cov_FSC_SSC": "PLTF RBC\ncov FSC SSC",
    "PLTF_RBC_cov_FSC_FSCW": "PLTF RBC\ncov FSC FSCW",
    "PLTF_RBC_cov_SSC_SSC": "PLTF RBC\ncov SSC SSC",
    "PLTF_RBC_cov_SSC_FSCW": "PLTF RBC\ncov SSC FSCW",
    "PLTF_RBC_cov_FSCW_FSCW": "PLTF RBC\ncov FSCW FSCW",
    "PLTF_WBC_mean_SFL": "PLTF WBC\nmean SFL",
    "PLTF_WBC_mean_FSC": "PLTF WBC\nmean FSC",
    "PLTF_WBC_mean_SSC": "PLTF WBC\nmean SSC",
    "PLTF_WBC_mean_FSCW": "PLTF WBC\nmean FSCW",
    "PLTF_WBC_cov_SFL_SFL": "PLTF WBC\ncov SFL SFL",
    "PLTF_WBC_cov_SFL_FSC": "PLTF WBC\ncov SFL FSC",
    "PLTF_WBC_cov_SFL_SSC": "PLTF WBC\ncov SFL SSC",
    "PLTF_WBC_cov_SFL_FSCW": "PLTF WBC\ncov SFL FSCW",
    "PLTF_WBC_cov_FSC_FSC": "PLTF WBC\ncov FSC FSC",
    "PLTF_WBC_cov_FSC_SSC": "PLTF WBC\ncov FSC SSC",
    "PLTF_WBC_cov_FSC_FSCW": "PLTF WBC\ncov FSC FSCW",
    "PLTF_WBC_cov_SSC_SSC": "PLTF WBC\ncov SSC SSC",
    "PLTF_WBC_cov_SSC_FSCW": "PLTF WBC\ncov SSC FSCW",
    "PLTF_WBC_cov_FSCW_FSCW": "PLTF WBC\ncov FSCW FSCW",
    "PLTF_PLT_mean_SFL": "PLTF PLT\nmean SFL",
    "PLTF_PLT_mean_FSC": "PLTF PLT\nmean FSC",
    "PLTF_PLT_mean_SSC": "PLTF PLT\nmean SSC",
    "PLTF_PLT_mean_FSCW": "PLTF PLT\nmean FSCW",
    "PLTF_PLT_cov_SFL_SFL": "PLTF PLT\ncov SFL SFL",
    "PLTF_PLT_cov_SFL_FSC": "PLTF PLT\ncov SFL FSC",
    "PLTF_PLT_cov_SFL_SSC": "PLTF PLT\ncov SFL SSC",
    "PLTF_PLT_cov_SFL_FSCW": "PLTF PLT\ncov SFL FSCW",
    "PLTF_PLT_cov_FSC_FSC": "PLTF PLT\ncov FSC FSC",
    "PLTF_PLT_cov_FSC_SSC": "PLTF PLT\ncov FSC SSC",
    "PLTF_PLT_cov_FSC_FSCW": "PLTF PLT\ncov FSC FSCW",
    "PLTF_PLT_cov_SSC_SSC": "PLTF PLT\ncov SSC SSC",
    "PLTF_PLT_cov_SSC_FSCW": "PLTF PLT\ncov SSC FSCW",
    "PLTF_PLT_cov_FSCW_FSCW": "PLTF PLT\ncov FSCW FSCW",
    "PLTF_immaturePLT_mean_SFL": "PLTF immaturePLT\nmean SFL",
    "PLTF_immaturePLT_mean_FSC": "PLTF immaturePLT\nmean FSC",
    "PLTF_immaturePLT_mean_SSC": "PLTF immaturePLT\nmean SSC",
    "PLTF_immaturePLT_mean_FSCW": "PLTF immaturePLT\nmean FSCW",
    "PLTF_immaturePLT_cov_SFL_SFL": "PLTF immaturePLT\ncov SFL SFL",
    "PLTF_immaturePLT_cov_SFL_FSC": "PLTF immaturePLT\ncov SFL FSC",
    "PLTF_immaturePLT_cov_SFL_SSC": "PLTF immaturePLT\ncov SFL SSC",
    "PLTF_immaturePLT_cov_SFL_FSCW": "PLTF immaturePLT\ncov SFL FSCW",
    "PLTF_immaturePLT_cov_FSC_FSC": "PLTF immaturePLT\ncov FSC FSC",
    "PLTF_immaturePLT_cov_FSC_SSC": "PLTF immaturePLT\ncov FSC SSC",
    "PLTF_immaturePLT_cov_FSC_FSCW": "PLTF immaturePLT\ncov FSC FSCW",
    "PLTF_immaturePLT_cov_SSC_SSC": "PLTF immaturePLT\ncov SSC SSC",
    "PLTF_immaturePLT_cov_SSC_FSCW": "PLTF immaturePLT\ncov SSC FSCW",
    "PLTF_immaturePLT_cov_FSCW_FSCW": "PLTF immaturePLT\ncov FSCW FSCW",
    "WNR_WBC_mean_SFL": "WNR WBC\nmean SFL",
    "WNR_WBC_mean_FSC": "WNR WBC\nmean FSC",
    "WNR_WBC_mean_SSC": "WNR WBC\nmean SSC",
    "WNR_WBC_mean_FSCW": "WNR WBC\nmean FSCW",
    "WNR_WBC_cov_SFL_SFL": "WNR WBC\ncov SFL SFL",
    "WNR_WBC_cov_SFL_FSC": "WNR WBC\ncov SFL FSC",
    "WNR_WBC_cov_SFL_SSC": "WNR WBC\ncov SFL SSC",
    "WNR_WBC_cov_SFL_FSCW": "WNR WBC\ncov SFL FSCW",
    "WNR_WBC_cov_FSC_FSC": "WNR WBC\ncov FSC FSC",
    "WNR_WBC_cov_FSC_SSC": "WNR WBC\ncov FSC SSC",
    "WNR_WBC_cov_FSC_FSCW": "WNR WBC\ncov FSC FSCW",
    "WNR_WBC_cov_SSC_SSC": "WNR WBC\ncov SSC SSC",
    "WNR_WBC_cov_SSC_FSCW": "WNR WBC\ncov SSC FSCW",
    "WNR_WBC_cov_FSCW_FSCW": "WNR WBC\ncov FSCW FSCW",
    "WNR_BASO_mean_SFL": "WNR BASO\nmean SFL",
    "WNR_BASO_mean_FSC": "WNR BASO\nmean FSC",
    "WNR_BASO_mean_SSC": "WNR BASO\nmean SSC",
    "WNR_BASO_mean_FSCW": "WNR BASO\nmean FSCW",
    "WNR_BASO_cov_SFL_SFL": "WNR BASO\ncov SFL SFL",
    "WNR_BASO_cov_SFL_FSC": "WNR BASO\ncov SFL FSC",
    "WNR_BASO_cov_SFL_SSC": "WNR BASO\ncov SFL SSC",
    "WNR_BASO_cov_SFL_FSCW": "WNR BASO\ncov SFL FSCW",
    "WNR_BASO_cov_FSC_FSC": "WNR BASO\ncov FSC FSC",
    "WNR_BASO_cov_FSC_SSC": "WNR BASO\ncov FSC SSC",
    "WNR_BASO_cov_FSC_FSCW": "WNR BASO\ncov FSC FSCW",
    "WNR_BASO_cov_SSC_SSC": "WNR BASO\ncov SSC SSC",
    "WNR_BASO_cov_SSC_FSCW": "WNR BASO\ncov SSC FSCW",
    "WNR_BASO_cov_FSCW_FSCW": "WNR BASO\ncov FSCW FSCW",
    "WNR_NRBC_mean_SFL": "WNR NRBC\nmean SFL",
    "WNR_NRBC_mean_FSC": "WNR NRBC\nmean FSC",
    "WNR_NRBC_mean_SSC": "WNR NRBC\nmean SSC",
    "WNR_NRBC_mean_FSCW": "WNR NRBC\nmean FSCW",
    "WNR_NRBC_cov_SFL_SFL": "WNR NRBC\ncov SFL SFL",
    "WNR_NRBC_cov_SFL_FSC": "WNR NRBC\ncov SFL FSC",
    "WNR_NRBC_cov_SFL_SSC": "WNR NRBC\ncov SFL SSC",
    "WNR_NRBC_cov_SFL_FSCW": "WNR NRBC\ncov SFL FSCW",
    "WNR_NRBC_cov_FSC_FSC": "WNR NRBC\ncov FSC FSC",
    "WNR_NRBC_cov_FSC_SSC": "WNR NRBC\ncov FSC SSC",
    "WNR_NRBC_cov_FSC_FSCW": "WNR NRBC\ncov FSC FSCW",
    "WNR_NRBC_cov_SSC_SSC": "WNR NRBC\ncov SSC SSC",
    "WNR_NRBC_cov_SSC_FSCW": "WNR NRBC\ncov SSC FSCW",
    "WNR_NRBC_cov_FSCW_FSCW": "WNR NRBC\ncov FSCW FSCW",
    "WDF_LYMPH_mean_SSC": "WDF LYMPH\nmean SSC",
    "WDF_LYMPH_mean_SFL": "WDF LYMPH\nmean SFL",
    "WDF_LYMPH_mean_FSC": "WDF LYMPH\nmean FSC",
    "WDF_LYMPH_mean_FSCW": "WDF LYMPH\nmean FSCW",
    "WDF_LYMPH_cov_SSC_SSC": "WDF LYMPH\ncov SSC SSC",
    "WDF_LYMPH_cov_SSC_SFL": "WDF LYMPH\ncov SSC SFL",
    "WDF_LYMPH_cov_SSC_FSC": "WDF LYMPH\ncov SSC FSC",
    "WDF_LYMPH_cov_SSC_FSCW": "WDF LYMPH\ncov SSC FSCW",
    "WDF_LYMPH_cov_SFL_SFL": "WDF LYMPH\ncov SFL SFL",
    "WDF_LYMPH_cov_SFL_FSC": "WDF LYMPH\ncov SFL FSC",
    "WDF_LYMPH_cov_SFL_FSCW": "WDF LYMPH\ncov SFL FSCW",
    "WDF_LYMPH_cov_FSC_FSC": "WDF LYMPH\ncov FSC FSC",
    "WDF_LYMPH_cov_FSC_FSCW": "WDF LYMPH\ncov FSC FSCW",
    "WDF_LYMPH_cov_FSCW_FSCW": "WDF LYMPH\ncov FSCW FSCW",
    "WDF_MONO_mean_SSC": "WDF MONO\nmean SSC",
    "WDF_MONO_mean_SFL": "WDF MONO\nmean SFL",
    "WDF_MONO_mean_FSC": "WDF MONO\nmean FSC",
    "WDF_MONO_mean_FSCW": "WDF MONO\nmean FSCW",
    "WDF_MONO_cov_SSC_SSC": "WDF MONO\ncov SSC SSC",
    "WDF_MONO_cov_SSC_SFL": "WDF MONO\ncov SSC SFL",
    "WDF_MONO_cov_SSC_FSC": "WDF MONO\ncov SSC FSC",
    "WDF_MONO_cov_SSC_FSCW": "WDF MONO\ncov SSC FSCW",
    "WDF_MONO_cov_SFL_SFL": "WDF MONO\ncov SFL SFL",
    "WDF_MONO_cov_SFL_FSC": "WDF MONO\ncov SFL FSC",
    "WDF_MONO_cov_SFL_FSCW": "WDF MONO\ncov SFL FSCW",
    "WDF_MONO_cov_FSC_FSC": "WDF MONO\ncov FSC FSC",
    "WDF_MONO_cov_FSC_FSCW": "WDF MONO\ncov FSC FSCW",
    "WDF_MONO_cov_FSCW_FSCW": "WDF MONO\ncov FSCW FSCW",
    "WDF_IG_mean_SSC": "WDF IG\nmean SSC",
    "WDF_IG_mean_SFL": "WDF IG\nmean SFL",
    "WDF_IG_mean_FSC": "WDF IG\nmean FSC",
    "WDF_IG_mean_FSCW": "WDF IG\nmean FSCW",
    "WDF_IG_cov_SSC_SSC": "WDF IG\ncov SSC SSC",
    "WDF_IG_cov_SSC_SFL": "WDF IG\ncov SSC SFL",
    "WDF_IG_cov_SSC_FSC": "WDF IG\ncov SSC FSC",
    "WDF_IG_cov_SSC_FSCW": "WDF IG\ncov SSC FSCW",
    "WDF_IG_cov_SFL_SFL": "WDF IG\ncov SFL SFL",
    "WDF_IG_cov_SFL_FSC": "WDF IG\ncov SFL FSC",
    "WDF_IG_cov_SFL_FSCW": "WDF IG\ncov SFL FSCW",
    "WDF_IG_cov_FSC_FSC": "WDF IG\ncov FSC FSC",
    "WDF_IG_cov_FSC_FSCW": "WDF IG\ncov FSC FSCW",
    "WDF_IG_cov_FSCW_FSCW": "WDF IG\ncov FSCW FSCW",
    "WDF_NEUTBASO_mean_SSC": "WDF NEUTBASO\nmean SSC",
    "WDF_NEUTBASO_mean_SFL": "WDF NEUTBASO\nmean SFL",
    "WDF_NEUTBASO_mean_FSC": "WDF NEUTBASO\nmean FSC",
    "WDF_NEUTBASO_mean_FSCW": "WDF NEUTBASO\nmean FSCW",
    "WDF_NEUTBASO_cov_SSC_SSC": "WDF NEUTBASO\ncov SSC SSC",
    "WDF_NEUTBASO_cov_SSC_SFL": "WDF NEUTBASO\ncov SSC SFL",
    "WDF_NEUTBASO_cov_SSC_FSC": "WDF NEUTBASO\ncov SSC FSC",
    "WDF_NEUTBASO_cov_SSC_FSCW": "WDF NEUTBASO\ncov SSC FSCW",
    "WDF_NEUTBASO_cov_SFL_SFL": "WDF NEUTBASO\ncov SFL SFL",
    "WDF_NEUTBASO_cov_SFL_FSC": "WDF NEUTBASO\ncov SFL FSC",
    "WDF_NEUTBASO_cov_SFL_FSCW": "WDF NEUTBASO\ncov SFL FSCW",
    "WDF_NEUTBASO_cov_FSC_FSC": "WDF NEUTBASO\ncov FSC FSC",
    "WDF_NEUTBASO_cov_FSC_FSCW": "WDF NEUTBASO\ncov FSC FSCW",
    "WDF_NEUTBASO_cov_FSCW_FSCW": "WDF NEUTBASO\ncov FSCW FSCW",
    "WDF_EO_mean_SSC": "WDF EO\nmean SSC",
    "WDF_EO_mean_SFL": "WDF EO\nmean SFL",
    "WDF_EO_mean_FSC": "WDF EO\nmean FSC",
    "WDF_EO_mean_FSCW": "WDF EO\nmean FSCW",
    "WDF_EO_cov_SSC_SSC": "WDF EO\ncov SSC SSC",
    "WDF_EO_cov_SSC_SFL": "WDF EO\ncov SSC SFL",
    "WDF_EO_cov_SSC_FSC": "WDF EO\ncov SSC FSC",
    "WDF_EO_cov_SSC_FSCW": "WDF EO\ncov SSC FSCW",
    "WDF_EO_cov_SFL_SFL": "WDF EO\ncov SFL SFL",
    "WDF_EO_cov_SFL_FSC": "WDF EO\ncov SFL FSC",
    "WDF_EO_cov_SFL_FSCW": "WDF EO\ncov SFL FSCW",
    "WDF_EO_cov_FSC_FSC": "WDF EO\ncov FSC FSC",
    "WDF_EO_cov_FSC_FSCW": "WDF EO\ncov FSC FSCW",
    "WDF_EO_cov_FSCW_FSCW": "WDF EO\ncov FSCW FSCW",
}


pretty_name_translation_dict_bl = {
    key + "_bl": value + " (0m)" for key, value in pretty_name_translation_dict.items()
}
pretty_name_translation_dict_24m = {
    key + "_24m": value + " (24m)"
    for key, value in pretty_name_translation_dict.items()
}
pretty_name_translation_dict_48m = {
    key + "_48m": value + " (48m)"
    for key, value in pretty_name_translation_dict.items()
}

pretty_name_translation_dict_diff_24m = {
    key + "_diff_24m": value + " (24m - 0m)"
    for key, value in pretty_name_translation_dict.items()
}

pretty_name_translation_dict_timepoints = {
    **pretty_name_translation_dict,
    **pretty_name_translation_dict_bl,
    **pretty_name_translation_dict_24m,
    **pretty_name_translation_dict_48m,
    **pretty_name_translation_dict_diff_24m,
}

# building RET, PLT-F, IP messages and Q-flags, and custom gaussians feature lists
ret_features = []
for feature in pretty_name_translation_dict.keys():
    if "RET" in feature:
        ret_features.append(feature)
    if "IRF" in feature:
        ret_features.append(feature)
    if "MFR" in feature:
        ret_features.append(feature)
    if "LFR" in feature:
        ret_features.append(feature)
    if "He" in feature:
        ret_features.append(feature)
    if "FRC" in feature:
        ret_features.append(feature)
    if "RBC-O" in feature:
        ret_features.append(feature)
    if "RBC-I" in feature:
        ret_features.append(feature)
    if "HGB-O" in feature:
        ret_features.append(feature)
    if "PLT-O" in feature:
        ret_features.append(feature)

plt_f_features = []
for feature in pretty_name_translation_dict.keys():
    if "PLT-F" in feature:
        plt_f_features.append(feature)
    if "PLTF" in feature:
        plt_f_features.append(feature)
    if "PLT-I" in feature:
        plt_f_features.append(feature)
    if "IPF" in feature:
        plt_f_features.append(feature)
    if "PLT-O" in feature:
        plt_f_features.append(feature)

ip_qflags_features = []
for feature in pretty_name_translation_dict.keys():
    if "IP " in feature:
        ip_qflags_features.append(feature)
    if "Q-Flag" in feature:
        ip_qflags_features.append(feature)

gaussian_features = []
for feature in pretty_name_translation_dict.keys():
    if "_mean_" in feature:
        gaussian_features.append(feature)
    if "_cov_" in feature:
        gaussian_features.append(feature)
